<?php

namespace OroCRMPro\Bundle\LDAPBundle\Tests\Unit\Stub;

use Oro\Bundle\UserBundle\Entity\User;

/**
 * Additional code is generated by entity extend bundle
 */
class TestingUser extends User
{
    /** @var array */
    protected $ldapDistinguishedNames;

    /**
     * @return string
     */
    public function getLdapDistinguishedNames()
    {
        return $this->ldapDistinguishedNames;
    }

    /**
     * @param string $ldapMappings
     *
     * @return TestingUser
     */
    public function setLdapDistinguishedNames($ldapMappings)
    {
        $this->ldapDistinguishedNames = $ldapMappings;

        return $this;
    }
}
