#!/usr/bin/env php
<?php


if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    echo "Can't find composer autoload file.\n Please run 'composer install'.\n";
    exit(1);
}

use Oro\Cli;

$app = new Cli\OroCliApplication();
$app->run();