<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AbsoluteMonthlyRecurrencePatternType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AbsoluteMonthlyRecurrencePatternType extends IntervalRecurrencePatternBaseType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $DayOfMonth;
}
// @codingStandardsIgnoreEnd
