<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AffectedTaskOccurrencesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AffectedTaskOccurrencesType
{
    const ALL_OCCURRENCES = "AllOccurrences";
    const SPECIFIED_OCCURRENCE_ONLY = "SpecifiedOccurrenceOnly";
}
// @codingStandardsIgnoreEnd
