<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * This max/min evaluation is applied to the field specified within the group by
 *         instance for EACH item within that group.  This determines which item from each group
 *         is to be selected as the representative for that group.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AggregateType
{
    const MINIMUM = "Minimum";
    const MAXIMUM = "Maximum";
}
// @codingStandardsIgnoreEnd
