<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Surfaces alternate representations of an item or folder id. No change key is included.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AlternateIdBaseType
{
    /**
     * @var string
     * @see IdFormatType
     * @access public
     */
    public $Format;
}
// @codingStandardsIgnoreEnd
