<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AppendToItemFieldType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AppendToItemFieldType extends ItemChangeDescriptionType
{
    /**
     * @var ItemType
     * @access public
     */
    public $Item;

    /**
     * @var MessageType
     * @access public
     */
    public $Message;

    /**
     * @var CalendarItemType
     * @access public
     */
    public $CalendarItem;

    /**
     * @var ContactItemType
     * @access public
     */
    public $Contact;

    /**
     * @var DistributionListType
     * @access public
     */
    public $DistributionList;

    /**
     * @var MeetingMessageType
     * @access public
     */
    public $MeetingMessage;

    /**
     * @var MeetingRequestMessageType
     * @access public
     */
    public $MeetingRequest;

    /**
     * @var MeetingResponseMessageType
     * @access public
     */
    public $MeetingResponse;

    /**
     * @var MeetingCancellationMessageType
     * @access public
     */
    public $MeetingCancellation;

    /**
     * @var TaskType
     * @access public
     */
    public $Task;

    /**
     * @var PostItemType
     * @access public
     */
    public $PostItem;
}
// @codingStandardsIgnoreEnd
