<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfSuggestion
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfSuggestion
{
    /**
     * @var Suggestion[]
     * @access public
     */
    public $Suggestion;
}
// @codingStandardsIgnoreEnd
