<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfTransitionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfTransitionsType
{
    /**
     * @var AbsoluteDateTransitionType[]
     * @access public
     */
    public $AbsoluteDateTransition;

    /**
     * @var RecurringDayTransitionType[]
     * @access public
     */
    public $RecurringDayTransition;

    /**
     * @var RecurringDateTransitionType[]
     * @access public
     */
    public $RecurringDateTransition;

    /**
     * @var TransitionType[]
     * @access public
     */
    public $Transition;

    /**
     * @var string
     * @access public
     */
    public $Id;
}
// @codingStandardsIgnoreEnd
