<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfCalendarEvent
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfCalendarEvent
{
    /**
     * @var CalendarEvent[]
     * @access public
     */
    public $CalendarEvent;
}
// @codingStandardsIgnoreEnd
