<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfResolutionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfResolutionType
{
    /**
     * @var ResolutionType
     * @access public
     */
    public $Resolution;
}
// @codingStandardsIgnoreEnd
