<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfAttendeeConflictData
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfAttendeeConflictData
{
    /**
     * @var UnknownAttendeeConflictData[]
     * @access public
     */
    public $UnknownAttendeeConflictData;

    /**
     * @var IndividualAttendeeConflictData[]
     * @access public
     */
    public $IndividualAttendeeConflictData;

    /**
     * @var TooBigGroupAttendeeConflictData[]
     * @access public
     */
    public $TooBigGroupAttendeeConflictData;

    /**
     * @var GroupAttendeeConflictData[]
     * @access public
     */
    public $GroupAttendeeConflictData;
}
// @codingStandardsIgnoreEnd
