<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfArraysOfTrackingPropertiesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfArraysOfTrackingPropertiesType
{
    /**
     * @var ArrayOfTrackingPropertiesType[]
     * @access public
     */
    public $ArrayOfTrackingPropertiesType;
}
// @codingStandardsIgnoreEnd
