<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfItemClassType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfItemClassType
{
    /**
     * @var string[] WSDL type is ItemClassType[]
     * @access public
     */
    public $ItemClass;
}
// @codingStandardsIgnoreEnd
