<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfPermissionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfPermissionsType
{
    /**
     * @var PermissionType[]
     * @access public
     */
    public $Permission;
}
// @codingStandardsIgnoreEnd
