<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfResponseMessagesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfResponseMessagesType
{
    /**
     * @var ItemInfoResponseMessageType[]
     * @access public
     */
    public $CreateItemResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $DeleteItemResponseMessage;

    /**
     * @var ItemInfoResponseMessageType[]
     * @access public
     */
    public $GetItemResponseMessage;

    /**
     * @var UpdateItemResponseMessageType[]
     * @access public
     */
    public $UpdateItemResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $SendItemResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $DeleteFolderResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $EmptyFolderResponseMessage;

    /**
     * @var FolderInfoResponseMessageType[]
     * @access public
     */
    public $CreateFolderResponseMessage;

    /**
     * @var FolderInfoResponseMessageType[]
     * @access public
     */
    public $GetFolderResponseMessage;

    /**
     * @var FindFolderResponseMessageType[]
     * @access public
     */
    public $FindFolderResponseMessage;

    /**
     * @var FolderInfoResponseMessageType[]
     * @access public
     */
    public $UpdateFolderResponseMessage;

    /**
     * @var FolderInfoResponseMessageType[]
     * @access public
     */
    public $MoveFolderResponseMessage;

    /**
     * @var FolderInfoResponseMessageType[]
     * @access public
     */
    public $CopyFolderResponseMessage;

    /**
     * @var AttachmentInfoResponseMessageType[]
     * @access public
     */
    public $CreateAttachmentResponseMessage;

    /**
     * @var DeleteAttachmentResponseMessageType[]
     * @access public
     */
    public $DeleteAttachmentResponseMessage;

    /**
     * @var AttachmentInfoResponseMessageType[]
     * @access public
     */
    public $GetAttachmentResponseMessage;

    /**
     * @var UploadItemsResponseMessageType[]
     * @access public
     */
    public $UploadItemsResponseMessage;

    /**
     * @var ExportItemsResponseMessageType[]
     * @access public
     */
    public $ExportItemsResponseMessage;

    /**
     * @var FindItemResponseMessageType[]
     * @access public
     */
    public $FindItemResponseMessage;

    /**
     * @var ItemInfoResponseMessageType[]
     * @access public
     */
    public $MoveItemResponseMessage;

    /**
     * @var ItemInfoResponseMessageType[]
     * @access public
     */
    public $CopyItemResponseMessage;

    /**
     * @var ResolveNamesResponseMessageType[]
     * @access public
     */
    public $ResolveNamesResponseMessage;

    /**
     * @var ExpandDLResponseMessageType[]
     * @access public
     */
    public $ExpandDLResponseMessage;

    /**
     * @var GetServerTimeZonesResponseMessageType[]
     * @access public
     */
    public $GetServerTimeZonesResponseMessage;

    /**
     * @var GetEventsResponseMessageType[]
     * @access public
     */
    public $GetEventsResponseMessage;

    /**
     * @var GetStreamingEventsResponseMessageType[]
     * @access public
     */
    public $GetStreamingEventsResponseMessage;

    /**
     * @var SubscribeResponseMessageType[]
     * @access public
     */
    public $SubscribeResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $UnsubscribeResponseMessage;

    /**
     * @var SendNotificationResponseMessageType[]
     * @access public
     */
    public $SendNotificationResponseMessage;

    /**
     * @var SyncFolderHierarchyResponseMessageType[]
     * @access public
     */
    public $SyncFolderHierarchyResponseMessage;

    /**
     * @var SyncFolderItemsResponseMessageType[]
     * @access public
     */
    public $SyncFolderItemsResponseMessage;

    /**
     * @var FolderInfoResponseMessageType[]
     * @access public
     */
    public $CreateManagedFolderResponseMessage;

    /**
     * @var ConvertIdResponseMessageType[]
     * @access public
     */
    public $ConvertIdResponseMessage;

    /**
     * @var GetSharingMetadataResponseMessageType[]
     * @access public
     */
    public $GetSharingMetadataResponseMessage;

    /**
     * @var RefreshSharingFolderResponseMessageType[]
     * @access public
     */
    public $RefreshSharingFolderResponseMessage;

    /**
     * @var GetSharingFolderResponseMessageType[]
     * @access public
     */
    public $GetSharingFolderResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $CreateUserConfigurationResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $DeleteUserConfigurationResponseMessage;

    /**
     * @var GetUserConfigurationResponseMessageType[]
     * @access public
     */
    public $GetUserConfigurationResponseMessage;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $UpdateUserConfigurationResponseMessage;

    /**
     * @var GetRoomListsResponseMessageType[]
     * @access public
     */
    public $GetRoomListsResponse;

    /**
     * @var GetRoomsResponseMessageType[]
     * @access public
     */
    public $GetRoomsResponse;

    /**
     * @var ResponseMessageType[]
     * @access public
     */
    public $ApplyConversationActionResponseMessage;

    /**
     * @var FindMailboxStatisticsByKeywordsResponseMessageType[]
     * @access public
     */
    public $FindMailboxStatisticsByKeywordsResponseMessage;

    /**
     * @var GetPasswordExpirationDateResponseMessageType[]
     * @access public
     */
    public $GetPasswordExpirationDateResponse;
}
// @codingStandardsIgnoreEnd
