<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Array of search item kind enum.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfSearchItemKindsType
{
    /**
     * @var string[]
     * @see SearchItemKindType
     * @access public
     */
    public $SearchItemKind;
}
// @codingStandardsIgnoreEnd
