<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfSmtpAddressType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfSmtpAddressType
{
    /**
     * @var string[] WSDL type is NonEmptyStringType[]
     * @access public
     */
    public $SmtpAddress;
}
// @codingStandardsIgnoreEnd
