<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfDLExpansionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfDLExpansionType
{
    /**
     * @var EmailAddressType[]
     * @access public
     */
    public $Mailbox;
}
// @codingStandardsIgnoreEnd
