<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfServiceConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfServiceConfigurationType
{
    /**
     * @var string[]
     * @see ServiceConfigurationType
     * @access public
     */
    public $ConfigurationName;
}
// @codingStandardsIgnoreEnd
