<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AttachmentInfoResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AttachmentInfoResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfAttachmentsType
     * @access public
     */
    public $Attachments;
}
// @codingStandardsIgnoreEnd
