<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AvailabilityProxyRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AvailabilityProxyRequestType
{
    const CROSS_SITE = "CrossSite";
    const CROSS_FOREST = "CrossForest";
}
// @codingStandardsIgnoreEnd
