<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * BaseMoveCopyFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class BaseMoveCopyFolderType extends BaseRequestType
{
    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $ToFolderId;

    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $FolderIds;
}
// @codingStandardsIgnoreEnd
