<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * BaseMoveCopyItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class BaseMoveCopyItemType extends BaseRequestType
{
    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $ToFolderId;

    /**
     * @var NonEmptyArrayOfBaseItemIdsType
     * @access public
     */
    public $ItemIds;

    /**
     * @var boolean
     * @access public
     */
    public $ReturnNewItemIds;
}
// @codingStandardsIgnoreEnd
