<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarEvent
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarEvent
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $StartTime;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $EndTime;

    /**
     * @var string
     * @see LegacyFreeBusyType
     * @access public
     */
    public $BusyType;

    /**
     * @var CalendarEventDetails
     * @access public
     */
    public $CalendarEventDetails;
}
// @codingStandardsIgnoreEnd
