<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarEventDetails
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarEventDetails
{
    /**
     * @var string
     * @access public
     */
    public $ID;

    /**
     * @var string
     * @access public
     */
    public $Subject;

    /**
     * @var string
     * @access public
     */
    public $Location;

    /**
     * @var boolean
     * @access public
     */
    public $IsMeeting;

    /**
     * @var boolean
     * @access public
     */
    public $IsRecurring;

    /**
     * @var boolean
     * @access public
     */
    public $IsException;

    /**
     * @var boolean
     * @access public
     */
    public $IsReminderSet;

    /**
     * @var boolean
     * @access public
     */
    public $IsPrivate;
}
// @codingStandardsIgnoreEnd
