<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarViewType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarViewType extends BasePagingType
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $StartDate;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $EndDate;
}
// @codingStandardsIgnoreEnd
