<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarPermissionReadAccessType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarPermissionReadAccessType
{
    const NONE = "None";
    const TIME_ONLY = "TimeOnly";
    const TIME_AND_SUBJECT_AND_LOCATION = "TimeAndSubjectAndLocation";
    const FULL_DETAILS = "FullDetails";
}
// @codingStandardsIgnoreEnd
