<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Type of conflict resolution to attempt during update
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConflictResolutionType
{
    const NEVER_OVERWRITE = "NeverOverwrite";
    const AUTO_RESOLVE = "AutoResolve";
    const ALWAYS_OVERWRITE = "AlwaysOverwrite";
}
// @codingStandardsIgnoreEnd
