<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ConnectionStatusType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConnectionStatusType
{
    const OK = "OK";
    const CLOSED = "Closed";
}
// @codingStandardsIgnoreEnd
