<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ContainsExpressionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ContainsExpressionType extends SearchExpressionType
{
    /**
     * @var PathToUnindexedFieldType[]
     * @access public
     */
    public $FieldURI;

    /**
     * @var PathToIndexedFieldType[]
     * @access public
     */
    public $IndexedFieldURI;

    /**
     * @var PathToExtendedFieldType[]
     * @access public
     */
    public $ExtendedFieldURI;

    /**
     * @var ConstantValueType
     * @access public
     */
    public $Constant;

    /**
     * @var string
     * @see ContainmentModeType
     * @access public
     */
    public $ContainmentMode;

    /**
     * @var string
     * @see ContainmentComparisonType
     * @access public
     */
    public $ContainmentComparison;
}
// @codingStandardsIgnoreEnd
