<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ContactItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ContactItemType extends ItemType
{
    /**
     * @var string
     * @access public
     */
    public $FileAs;

    /**
     * @var string
     * @see FileAsMappingType
     * @access public
     */
    public $FileAsMapping;

    /**
     * @var string
     * @access public
     */
    public $DisplayName;

    /**
     * @var string
     * @access public
     */
    public $GivenName;

    /**
     * @var string
     * @access public
     */
    public $Initials;

    /**
     * @var string
     * @access public
     */
    public $MiddleName;

    /**
     * @var string
     * @access public
     */
    public $Nickname;

    /**
     * @var CompleteNameType
     * @access public
     */
    public $CompleteName;

    /**
     * @var string
     * @access public
     */
    public $CompanyName;

    /**
     * @var EmailAddressDictionaryType
     * @access public
     */
    public $EmailAddresses;

    /**
     * @var PhysicalAddressDictionaryType
     * @access public
     */
    public $PhysicalAddresses;

    /**
     * @var PhoneNumberDictionaryType
     * @access public
     */
    public $PhoneNumbers;

    /**
     * @var string
     * @access public
     */
    public $AssistantName;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $Birthday;

    /**
     * @var anyURI
     * @access public
     */
    public $BusinessHomePage;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Children;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Companies;

    /**
     * @var string
     * @see ContactSourceType
     * @access public
     */
    public $ContactSource;

    /**
     * @var string
     * @access public
     */
    public $Department;

    /**
     * @var string
     * @access public
     */
    public $Generation;

    /**
     * @var ImAddressDictionaryType
     * @access public
     */
    public $ImAddresses;

    /**
     * @var string
     * @access public
     */
    public $JobTitle;

    /**
     * @var string
     * @access public
     */
    public $Manager;

    /**
     * @var string
     * @access public
     */
    public $Mileage;

    /**
     * @var string
     * @access public
     */
    public $OfficeLocation;

    /**
     * @var string
     * @see PhysicalAddressIndexType
     * @access public
     */
    public $PostalAddressIndex;

    /**
     * @var string
     * @access public
     */
    public $Profession;

    /**
     * @var string
     * @access public
     */
    public $SpouseName;

    /**
     * @var string
     * @access public
     */
    public $Surname;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $WeddingAnniversary;

    /**
     * @var boolean
     * @access public
     */
    public $HasPicture;

    /**
     * @var string
     * @access public
     */
    public $PhoneticFullName;

    /**
     * @var string
     * @access public
     */
    public $PhoneticFirstName;

    /**
     * @var string
     * @access public
     */
    public $PhoneticLastName;

    /**
     * @var string
     * @access public
     */
    public $Alias;

    /**
     * @var string
     * @access public
     */
    public $Notes;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $Photo;

    /**
     * @var ArrayOfBinaryType
     * @access public
     */
    public $UserSMIMECertificate;

    /**
     * @var ArrayOfBinaryType
     * @access public
     */
    public $MSExchangeCertificate;

    /**
     * @var string
     * @access public
     */
    public $DirectoryId;

    /**
     * @var SingleRecipientType
     * @access public
     */
    public $ManagerMailbox;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $DirectReports;
}
// @codingStandardsIgnoreEnd
