<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ContactsViewType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ContactsViewType extends BasePagingType
{
    /**
     * @var string
     * @access public
     */
    public $InitialName;

    /**
     * @var string
     * @access public
     */
    public $FinalName;
}
// @codingStandardsIgnoreEnd
