<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ContainmentModeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ContainmentModeType
{
    const FULL_STRING = "FullString";
    const PREFIXED = "Prefixed";
    const SUBSTRING = "Substring";
    const PREFIX_ON_WORDS = "PrefixOnWords";
    const EXACT_PHRASE = "ExactPhrase";
}
// @codingStandardsIgnoreEnd
