<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ConversationActionTypeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConversationActionTypeType
{
    const ALWAYS_CATEGORIZE = "AlwaysCategorize";
    const ALWAYS_DELETE = "AlwaysDelete";
    const ALWAYS_MOVE = "AlwaysMove";
    const DELETE = "Delete";
    const MOVE = "Move";
    const COPY = "Copy";
    const SET_READ_STATE = "SetReadState";
}
// @codingStandardsIgnoreEnd
