<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Converts the passed source ids into the destination format.  Change keys are not
 *                 returned.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConvertIdType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfAlternateIdsType
     * @access public
     */
    public $SourceIds;

    /**
     * @var string
     * @see IdFormatType
     * @access public
     */
    public $DestinationFormat;
}
// @codingStandardsIgnoreEnd
