<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Precision for returned DateTime values
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DateTimePrecisionType
{
    const SECONDS = "Seconds";
    const MILLISECONDS = "Milliseconds";
}
// @codingStandardsIgnoreEnd
