<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DayOfWeekIndexType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DayOfWeekIndexType
{
    const FIRST = "First";
    const SECOND = "Second";
    const THIRD = "Third";
    const FOURTH = "Fourth";
    const LAST = "Last";
}
// @codingStandardsIgnoreEnd
