<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DayOfWeekType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DayOfWeekType
{
    const SUNDAY = "Sunday";
    const MONDAY = "Monday";
    const TUESDAY = "Tuesday";
    const WEDNESDAY = "Wednesday";
    const THURSDAY = "Thursday";
    const FRIDAY = "Friday";
    const SATURDAY = "Saturday";
    const DAY = "Day";
    const WEEKDAY = "Weekday";
    const WEEKEND_DAY = "WeekendDay";
}
// @codingStandardsIgnoreEnd
