<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DeleteAttachmentResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DeleteAttachmentResponseMessageType extends ResponseMessageType
{
    /**
     * @var RootItemIdType
     * @access public
     */
    public $RootItemId;
}
// @codingStandardsIgnoreEnd
