<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DelegateFolderPermissionLevelType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DelegateFolderPermissionLevelType
{
    const NONE = "None";
    const EDITOR = "Editor";
    const REVIEWER = "Reviewer";
    const AUTHOR = "Author";
    const CUSTOM = "Custom";
}
// @codingStandardsIgnoreEnd
