<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DelegateUserResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DelegateUserResponseMessageType extends ResponseMessageType
{
    /**
     * @var DelegateUserType
     * @access public
     */
    public $DelegateUser;
}
// @codingStandardsIgnoreEnd
