<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DeleteUserConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DeleteUserConfigurationType extends BaseRequestType
{
    /**
     * @var UserConfigurationNameType
     * @access public
     */
    public $UserConfigurationName;
}
// @codingStandardsIgnoreEnd
