<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DelegatePermissionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DelegatePermissionsType
{
    /**
     * @var string
     * @see DelegateFolderPermissionLevelType
     * @access public
     */
    public $CalendarFolderPermissionLevel;

    /**
     * @var string
     * @see DelegateFolderPermissionLevelType
     * @access public
     */
    public $TasksFolderPermissionLevel;

    /**
     * @var string
     * @see DelegateFolderPermissionLevelType
     * @access public
     */
    public $InboxFolderPermissionLevel;

    /**
     * @var string
     * @see DelegateFolderPermissionLevelType
     * @access public
     */
    public $ContactsFolderPermissionLevel;

    /**
     * @var string
     * @see DelegateFolderPermissionLevelType
     * @access public
     */
    public $NotesFolderPermissionLevel;

    /**
     * @var string
     * @see DelegateFolderPermissionLevelType
     * @access public
     */
    public $JournalFolderPermissionLevel;
}
// @codingStandardsIgnoreEnd
