<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DelegateUserType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DelegateUserType
{
    /**
     * @var UserIdType
     * @access public
     */
    public $UserId;

    /**
     * @var DelegatePermissionsType
     * @access public
     */
    public $DelegatePermissions;

    /**
     * @var boolean
     * @access public
     */
    public $ReceiveCopiesOfMeetingMessages;

    /**
     * @var boolean
     * @access public
     */
    public $ViewPrivateItems;
}
// @codingStandardsIgnoreEnd
