<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DeliverMeetingRequestsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DeliverMeetingRequestsType
{
    const DELEGATES_ONLY = "DelegatesOnly";
    const DELEGATES_AND_ME = "DelegatesAndMe";
    const DELEGATES_AND_SEND_INFORMATION_TO_ME = "DelegatesAndSendInformationToMe";
    const NO_FORWARD = "NoForward";
}
// @codingStandardsIgnoreEnd
