<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Defines the well known property set ids for extended properties.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DistinguishedPropertySetType
{
    const MEETING = "Meeting";
    const APPOINTMENT = "Appointment";
    const COMMON = "Common";
    const PUBLIC_STRINGS = "PublicStrings";
    const ADDRESS = "Address";
    const INTERNET_HEADERS = "InternetHeaders";
    const CALENDAR_ASSISTANT = "CalendarAssistant";
    const UNIFIED_MESSAGING = "UnifiedMessaging";
    const TASK = "Task";
}
// @codingStandardsIgnoreEnd
