<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DistributionListType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DistributionListType extends ItemType
{
    /**
     * @var string
     * @access public
     */
    public $DisplayName;

    /**
     * @var string
     * @access public
     */
    public $FileAs;

    /**
     * @var string
     * @see ContactSourceType
     * @access public
     */
    public $ContactSource;

    /**
     * @var MembersListType
     * @access public
     */
    public $Members;
}
// @codingStandardsIgnoreEnd
