<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Identifier for a distinguished folder
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DistinguishedFolderIdType extends BaseFolderIdType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $Mailbox;

    /**
     * @var string
     * @see DistinguishedFolderIdNameType
     * @access public
     */
    public $Id;

    /**
     * @var string
     * @access public
     */
    public $ChangeKey;
}
// @codingStandardsIgnoreEnd
