<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Duration
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class Duration
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $StartTime;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $EndTime;
}
// @codingStandardsIgnoreEnd
