<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Identifier for a fully resolved email address
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EmailAddressType extends BaseEmailAddressType
{
    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $EmailAddress;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $RoutingType;

    /**
     * @var string
     * @see MailboxTypeType
     * @access public
     */
    public $MailboxType;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;
}
// @codingStandardsIgnoreEnd
