<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EncryptedSharedFolderDataType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EncryptedSharedFolderDataType
{
    /**
     * @var EncryptedDataContainerType
     * @access public
     */
    public $Token;

    /**
     * @var EncryptedDataContainerType
     * @access public
     */
    public $Data;
}
// @codingStandardsIgnoreEnd
