<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExceptionPropertyURIType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExceptionPropertyURIType
{
    const ATTACHMENT_NAME = "attachment:Name";
    const ATTACHMENT_CONTENT_TYPE = "attachment:ContentType";
    const ATTACHMENT_CONTENT = "attachment:Content";
    const RECURRENCE_MONTH = "recurrence:Month";
    const RECURRENCE_DAY_OF_WEEK_INDEX = "recurrence:DayOfWeekIndex";
    const RECURRENCE_DAYS_OF_WEEK = "recurrence:DaysOfWeek";
    const RECURRENCE_DAY_OF_MONTH = "recurrence:DayOfMonth";
    const RECURRENCE_INTERVAL = "recurrence:Interval";
    const RECURRENCE_NUMBER_OF_OCCURRENCES = "recurrence:NumberOfOccurrences";
    const TIMEZONE_OFFSET = "timezone:Offset";
}
// @codingStandardsIgnoreEnd
