<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExchangeVersionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExchangeVersionType
{
    const EXCHANGE2007 = "Exchange2007";
    const EXCHANGE2007_SP1 = "Exchange2007_SP1";
    const EXCHANGE2010 = "Exchange2010";
    const EXCHANGE2010_SP1 = "Exchange2010_SP1";
    const EXCHANGE2010_SP2 = "Exchange2010_SP2";
}
// @codingStandardsIgnoreEnd
