<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExpandDLResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExpandDLResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfDLExpansionType
     * @access public
     */
    public $DLExpansion;
}
// @codingStandardsIgnoreEnd
