<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExpandDLType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExpandDLType extends BaseRequestType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $Mailbox;
}
// @codingStandardsIgnoreEnd
