<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents an extended property instance (both its path identifier along with its
 *         associated value).
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExtendedPropertyType
{
    /**
     * @var PathToExtendedFieldType
     * @access public
     */
    public $ExtendedFieldURI;

    /**
     * @var string
     * @access public
     */
    public $Value;

    /**
     * @var NonEmptyArrayOfPropertyValuesType
     * @access public
     */
    public $Values;
}
// @codingStandardsIgnoreEnd
