<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FileAsMappingType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FileAsMappingType
{
    const NONE = "None";
    const LAST_COMMA_FIRST = "LastCommaFirst";
    const FIRST_SPACE_LAST = "FirstSpaceLast";
    const COMPANY = "Company";
    const LAST_COMMA_FIRST_COMPANY = "LastCommaFirstCompany";
    const COMPANY_LAST_FIRST = "CompanyLastFirst";
    const LAST_FIRST = "LastFirst";
    const LAST_FIRST_COMPANY = "LastFirstCompany";
    const COMPANY_LAST_COMMA_FIRST = "CompanyLastCommaFirst";
    const LAST_FIRST_SUFFIX = "LastFirstSuffix";
    const LAST_SPACE_FIRST_COMPANY = "LastSpaceFirstCompany";
    const COMPANY_LAST_SPACE_FIRST = "CompanyLastSpaceFirst";
    const LAST_SPACE_FIRST = "LastSpaceFirst";
    const DISPLAY_NAME = "DisplayName";
    const FIRST_NAME = "FirstName";
    const LAST_FIRST_MIDDLE_SUFFIX = "LastFirstMiddleSuffix";
    const LAST_NAME = "LastName";
    /**
     * The name was changed based on a name map provided to the PHP code generation tool
    */
    const EMPTY_DATA = "Empty";
}
// @codingStandardsIgnoreEnd
