<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindItemType extends BaseRequestType
{
    /**
     * @var ItemResponseShapeType
     * @access public
     */
    public $ItemShape;

    /**
     * @var IndexedPageViewType
     * @access public
     */
    public $IndexedPageItemView;

    /**
     * @var FractionalPageViewType
     * @access public
     */
    public $FractionalPageItemView;

    /**
     * @var CalendarViewType
     * @access public
     */
    public $CalendarView;

    /**
     * @var ContactsViewType
     * @access public
     */
    public $ContactsView;

    /**
     * @var GroupByType
     * @access public
     */
    public $GroupBy;

    /**
     * @var DistinguishedGroupByType
     * @access public
     */
    public $DistinguishedGroupBy;

    /**
     * @var RestrictionType
     * @access public
     */
    public $Restriction;

    /**
     * @var NonEmptyArrayOfFieldOrdersType
     * @access public
     */
    public $SortOrder;

    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $ParentFolderIds;

    /**
     * @var string
     * @access public
     */
    public $QueryString;

    /**
     * @var string
     * @see ItemQueryTraversalType
     * @access public
     */
    public $Traversal;
}
// @codingStandardsIgnoreEnd
