<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindMessageTrackingSearchResultType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindMessageTrackingSearchResultType
{
    /**
     * @var string
     * @access public
     */
    public $Subject;

    /**
     * @var EmailAddressType
     * @access public
     */
    public $Sender;

    /**
     * @var EmailAddressType
     * @access public
     */
    public $PurportedSender;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $Recipients;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $SubmittedTime;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $MessageTrackingReportId;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $PreviousHopServer;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $FirstHopServer;

    /**
     * @var ArrayOfTrackingPropertiesType
     * @access public
     */
    public $Properties;
}
// @codingStandardsIgnoreEnd
