<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindItemResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindItemResponseMessageType extends ResponseMessageType
{
    /**
     * @var FindItemParentType
     * @access public
     */
    public $RootFolder;
}
// @codingStandardsIgnoreEnd
