<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Request type for the FindMailboxStatisticsByKeywords web method.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindMailboxStatisticsByKeywordsType extends BaseRequestType
{
    /**
     * @var ArrayOfUserMailboxesType
     * @access public
     */
    public $Mailboxes;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Keywords;

    /**
     * @var string
     * @access public
     */
    public $Language;

    /**
     * @var ArrayOfSmtpAddressType
     * @access public
     */
    public $Senders;

    /**
     * @var ArrayOfSmtpAddressType
     * @access public
     */
    public $Recipients;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $FromDate;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $ToDate;

    /**
     * @var ArrayOfSearchItemKindsType
     * @access public
     */
    public $MessageTypes;

    /**
     * @var boolean
     * @access public
     */
    public $SearchDumpster;

    /**
     * @var boolean
     * @access public
     */
    public $IncludePersonalArchive;

    /**
     * @var boolean
     * @access public
     */
    public $IncludeUnsearchableItems;
}
// @codingStandardsIgnoreEnd
