<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Response message type for the FindMailboxStatisticsByKeywords web method.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindMailboxStatisticsByKeywordsResponseMessageType extends ResponseMessageType
{
    /**
     * @var MailboxStatisticsSearchResultType
     * @access public
     */
    public $MailboxStatisticsSearchResult;
}
// @codingStandardsIgnoreEnd
