<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindConversationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindConversationType extends BaseRequestType
{
    /**
     * @var IndexedPageViewType
     * @access public
     */
    public $IndexedPageItemView;

    /**
     * @var NonEmptyArrayOfFieldOrdersType
     * @access public
     */
    public $SortOrder;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $ParentFolderId;
}
// @codingStandardsIgnoreEnd
