<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FlagStatusType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FlagStatusType
{
    const NOT_FLAGGED = "NotFlagged";
    const FLAGGED = "Flagged";
    const COMPLETE = "Complete";
}
// @codingStandardsIgnoreEnd
