<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FractionalPageViewType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FractionalPageViewType extends BasePagingType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Numerator;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Denominator;
}
// @codingStandardsIgnoreEnd
