<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FreeBusyViewOptionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FreeBusyViewOptionsType
{
    /**
     * @var Duration
     * @access public
     */
    public $TimeWindow;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MergedFreeBusyIntervalInMinutes;

    /**
     * @var string
     * @see FreeBusyViewType
     * @access public
     */
    public $RequestedView;
}
// @codingStandardsIgnoreEnd
