<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetDelegateResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetDelegateResponseMessageType extends BaseDelegateResponseMessageType
{
    /**
     * @var string
     * @see DeliverMeetingRequestsType
     * @access public
     */
    public $DeliverMeetingRequests;
}
// @codingStandardsIgnoreEnd
