<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetDelegateType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetDelegateType extends BaseDelegateType
{
    /**
     * @var ArrayOfUserIdType
     * @access public
     */
    public $UserIds;

    /**
     * @var boolean
     * @access public
     */
    public $IncludePermissions;
}
// @codingStandardsIgnoreEnd
