<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetFolderType extends BaseRequestType
{
    /**
     * @var FolderResponseShapeType
     * @access public
     */
    public $FolderShape;

    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $FolderIds;
}
// @codingStandardsIgnoreEnd
