<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetMessageTrackingReportRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetMessageTrackingReportRequestType extends BaseRequestType
{
    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $Scope;

    /**
     * @var string
     * @see MessageTrackingReportTemplateType
     * @access public
     */
    public $ReportTemplate;

    /**
     * @var EmailAddressType
     * @access public
     */
    public $RecipientFilter;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $MessageTrackingReportId;

    /**
     * @var boolean
     * @access public
     */
    public $ReturnQueueEvents;

    /**
     * @var string
     * @access public
     */
    public $DiagnosticsLevel;

    /**
     * @var ArrayOfTrackingPropertiesType
     * @access public
     */
    public $Properties;
}
// @codingStandardsIgnoreEnd
