<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetMailTipsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetMailTipsType extends BaseRequestType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $SendingAs;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $Recipients;

    /**
     * @var string
     * @see MailTipTypes
     * @access public
     */
    public $MailTipsRequested;
}
// @codingStandardsIgnoreEnd
