<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetPhoneCallInformationResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetPhoneCallInformationResponseMessageType extends ResponseMessageType
{
    /**
     * @var PhoneCallInformationType
     * @access public
     */
    public $PhoneCallInformation;
}
// @codingStandardsIgnoreEnd
