<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetServerTimeZonesResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetServerTimeZonesResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfTimeZoneDefinitionType
     * @access public
     */
    public $TimeZoneDefinitions;
}
// @codingStandardsIgnoreEnd
