<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetSharingMetadataResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetSharingMetadataResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfEncryptedSharedFolderDataType
     * @access public
     */
    public $EncryptedSharedFolderDataCollection;

    /**
     * @var ArrayOfInvalidRecipientsType
     * @access public
     */
    public $InvalidRecipients;
}
// @codingStandardsIgnoreEnd
