<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetServerTimeZonesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetServerTimeZonesType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfTimeZoneIdType
     * @access public
     */
    public $Ids;

    /**
     * @var boolean
     * @access public
     */
    public $ReturnFullTimeZoneData;
}
// @codingStandardsIgnoreEnd
