<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetStreamingEventsResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetStreamingEventsResponseMessageType extends ResponseMessageType
{
    /**
     * @var NonEmptyArrayOfNotificationsType
     * @access public
     */
    public $Notifications;

    /**
     * @var NonEmptyArrayOfSubscriptionIdsType
     * @access public
     */
    public $ErrorSubscriptionIds;

    /**
     * @var string
     * @see ConnectionStatusType
     * @access public
     */
    public $ConnectionStatus;
}
// @codingStandardsIgnoreEnd
