<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Allows consumers to specify arbitrary groupings for FindItem queries.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GroupByType extends BaseGroupByType
{
    /**
     * @var PathToUnindexedFieldType
     * @access public
     */
    public $FieldURI;

    /**
     * @var PathToIndexedFieldType
     * @access public
     */
    public $IndexedFieldURI;

    /**
     * @var PathToExtendedFieldType
     * @access public
     */
    public $ExtendedFieldURI;

    /**
     * @var AggregateOnType
     * @access public
     */
    public $AggregateOn;
}
// @codingStandardsIgnoreEnd
