<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Surfaces the various id types that are supported for conversion
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class IdFormatType
{
    const EWS_LEGACY_ID = "EwsLegacyId";
    const EWS_ID = "EwsId";
    const ENTRY_ID = "EntryId";
    const HEX_ENTRY_ID = "HexEntryId";
    const STORE_ID = "StoreId";
    const OWA_ID = "OwaId";
}
// @codingStandardsIgnoreEnd
