<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ImAddressKeyType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ImAddressKeyType
{
    const IM_ADDRESS1 = "ImAddress1";
    const IM_ADDRESS2 = "ImAddress2";
    const IM_ADDRESS3 = "ImAddress3";
}
// @codingStandardsIgnoreEnd
