<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * IndexBasePointType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class IndexBasePointType
{
    const BEGINNING = "Beginning";
    const END = "End";
}
// @codingStandardsIgnoreEnd
