<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * IndividualAttendeeConflictData
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class IndividualAttendeeConflictData extends AttendeeConflictData
{
    /**
     * @var string
     * @see LegacyFreeBusyType
     * @access public
     */
    public $BusyType;
}
// @codingStandardsIgnoreEnd
