<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * InvalidRecipientType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class InvalidRecipientType
{
    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $SmtpAddress;

    /**
     * @var string
     * @see InvalidRecipientResponseCodeType
     * @access public
     */
    public $ResponseCode;

    /**
     * @var string
     * @access public
     */
    public $MessageText;
}
// @codingStandardsIgnoreEnd
