<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ItemChangeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ItemChangeType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var OccurrenceItemIdType
     * @access public
     */
    public $OccurrenceItemId;

    /**
     * @var RecurringMasterItemIdType
     * @access public
     */
    public $RecurringMasterItemId;

    /**
     * @var NonEmptyArrayOfItemChangeDescriptionsType
     * @access public
     */
    public $Updates;
}
// @codingStandardsIgnoreEnd
