<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ItemType
{
    /**
     * @var MimeContentType
     * @access public
     */
    public $MimeContent;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var FolderIdType
     * @access public
     */
    public $ParentFolderId;

    /**
     * @var string WSDL type is ItemClassType
     * @access public
     */
    public $ItemClass;

    /**
     * @var string
     * @access public
     */
    public $Subject;

    /**
     * @var string
     * @see SensitivityChoicesType
     * @access public
     */
    public $Sensitivity;

    /**
     * @var BodyType
     * @access public
     */
    public $Body;

    /**
     * @var NonEmptyArrayOfAttachmentsType
     * @access public
     */
    public $Attachments;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $DateTimeReceived;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Size;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Categories;

    /**
     * @var string
     * @see ImportanceChoicesType
     * @access public
     */
    public $Importance;

    /**
     * @var string
     * @access public
     */
    public $InReplyTo;

    /**
     * @var boolean
     * @access public
     */
    public $IsSubmitted;

    /**
     * @var boolean
     * @access public
     */
    public $IsDraft;

    /**
     * @var boolean
     * @access public
     */
    public $IsFromMe;

    /**
     * @var boolean
     * @access public
     */
    public $IsResend;

    /**
     * @var boolean
     * @access public
     */
    public $IsUnmodified;

    /**
     * @var NonEmptyArrayOfInternetHeadersType
     * @access public
     */
    public $InternetMessageHeaders;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $DateTimeSent;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $DateTimeCreated;

    /**
     * @var NonEmptyArrayOfResponseObjectsType
     * @access public
     */
    public $ResponseObjects;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $ReminderDueBy;

    /**
     * @var boolean
     * @access public
     */
    public $ReminderIsSet;

    /**
     * @var integer WSDL type is ReminderMinutesBeforeStartType
     * @access public
     */
    public $ReminderMinutesBeforeStart;

    /**
     * @var string
     * @access public
     */
    public $DisplayCc;

    /**
     * @var string
     * @access public
     */
    public $DisplayTo;

    /**
     * @var boolean
     * @access public
     */
    public $HasAttachments;

    /**
     * @var ExtendedPropertyType[]
     * @access public
     */
    public $ExtendedProperty;

    /**
     * @var string WSDL type is language
     * @access public
     */
    public $Culture;

    /**
     * @var EffectiveRightsType
     * @access public
     */
    public $EffectiveRights;

    /**
     * @var string
     * @access public
     */
    public $LastModifiedName;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $LastModifiedTime;

    /**
     * @var boolean
     * @access public
     */
    public $IsAssociated;

    /**
     * @var string
     * @access public
     */
    public $WebClientReadFormQueryString;

    /**
     * @var string
     * @access public
     */
    public $WebClientEditFormQueryString;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ConversationId;

    /**
     * @var BodyType
     * @access public
     */
    public $UniqueBody;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $StoreEntryId;
}
// @codingStandardsIgnoreEnd
