<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ItemResponseShapeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ItemResponseShapeType
{
    /**
     * @var string
     * @see DefaultShapeNamesType
     * @access public
     */
    public $BaseShape;

    /**
     * @var boolean
     * @access public
     */
    public $IncludeMimeContent;

    /**
     * @var string
     * @see BodyTypeResponseType
     * @access public
     */
    public $BodyType;

    /**
     * @var boolean
     * @access public
     */
    public $FilterHtmlContent;

    /**
     * @var boolean
     * @access public
     */
    public $ConvertHtmlCodePageToUTF8;

    /**
     * @var NonEmptyArrayOfPathsToElementType
     * @access public
     */
    public $AdditionalProperties;
}
// @codingStandardsIgnoreEnd
