<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * LegacyFreeBusyType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class LegacyFreeBusyType
{
    const FREE = "Free";
    const TENTATIVE = "Tentative";
    const BUSY = "Busy";
    const OOF = "OOF";
    const NO_DATA = "NoData";
}
// @codingStandardsIgnoreEnd
