<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MailTipTypes
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MailTipTypes
{
    const ALL = "All";
    const OUT_OF_OFFICE_MESSAGE = "OutOfOfficeMessage";
    const MAILBOX_FULL_STATUS = "MailboxFullStatus";
    const CUSTOM_MAIL_TIP = "CustomMailTip";
    const EXTERNAL_MEMBER_COUNT = "ExternalMemberCount";
    const TOTAL_MEMBER_COUNT = "TotalMemberCount";
    const MAX_MESSAGE_SIZE = "MaxMessageSize";
    const DELIVERY_RESTRICTION = "DeliveryRestriction";
    const MODERATION_STATUS = "ModerationStatus";
    const INVALID_RECIPIENT = "InvalidRecipient";
}
// @codingStandardsIgnoreEnd
