<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MailboxData
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MailboxData
{
    /**
     * @var EmailAddress
     * @access public
     */
    public $Email;

    /**
     * @var string
     * @see MeetingAttendeeType
     * @access public
     */
    public $AttendeeType;

    /**
     * @var boolean
     * @access public
     */
    public $ExcludeConflicts;
}
// @codingStandardsIgnoreEnd
