<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Mailbox statistics search result.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MailboxStatisticsSearchResultType
{
    /**
     * @var UserMailboxType
     * @access public
     */
    public $UserMailbox;

    /**
     * @var KeywordStatisticsSearchResultType
     * @access public
     */
    public $KeywordStatisticsSearchResult;
}
// @codingStandardsIgnoreEnd
