<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MessageDispositionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MessageDispositionType
{
    const SAVE_ONLY = "SaveOnly";
    const SEND_ONLY = "SendOnly";
    const SEND_AND_SAVE_COPY = "SendAndSaveCopy";
}
// @codingStandardsIgnoreEnd
