<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MimeContentType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MimeContentType
{
    /**
     * @var string
     * @access public
     */
    // @codingStandardsIgnoreStart
    public $_;
    // @codingStandardsIgnoreEnd

    /**
     * @var string
     * @access public
     */
    public $CharacterSet;
}
// @codingStandardsIgnoreEnd
