<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MonthNamesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MonthNamesType
{
    const JANUARY = "January";
    const FEBRUARY = "February";
    const MARCH = "March";
    const APRIL = "April";
    const MAY = "May";
    const JUNE = "June";
    const JULY = "July";
    const AUGUST = "August";
    const SEPTEMBER = "September";
    const OCTOBER = "October";
    const NOVEMBER = "November";
    const DECEMBER = "December";
}
// @codingStandardsIgnoreEnd
