<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfPathsToElementType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfPathsToElementType
{
    /**
     * @var PathToUnindexedFieldType[]
     * @access public
     */
    public $FieldURI;

    /**
     * @var PathToIndexedFieldType[]
     * @access public
     */
    public $IndexedFieldURI;

    /**
     * @var PathToExtendedFieldType[]
     * @access public
     */
    public $ExtendedFieldURI;
}
// @codingStandardsIgnoreEnd
