<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * A non-empty array of alternate Ids.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfAlternateIdsType
{
    /**
     * @var AlternateIdType[]
     * @access public
     */
    public $AlternateId;

    /**
     * @var AlternatePublicFolderIdType[]
     * @access public
     */
    public $AlternatePublicFolderId;

    /**
     * @var AlternatePublicFolderItemIdType[]
     * @access public
     */
    public $AlternatePublicFolderItemId;
}
// @codingStandardsIgnoreEnd
