<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfSubscriptionIdsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfSubscriptionIdsType
{
    /**
     * @var string[] WSDL type is SubscriptionIdType[]
     * @access public
     */
    public $SubscriptionId;
}
// @codingStandardsIgnoreEnd
