<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfResponseObjectsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfResponseObjectsType
{
    /**
     * @var AcceptItemType[]
     * @access public
     */
    public $AcceptItem;

    /**
     * @var TentativelyAcceptItemType[]
     * @access public
     */
    public $TentativelyAcceptItem;

    /**
     * @var DeclineItemType[]
     * @access public
     */
    public $DeclineItem;

    /**
     * @var ReplyToItemType[]
     * @access public
     */
    public $ReplyToItem;

    /**
     * @var ForwardItemType[]
     * @access public
     */
    public $ForwardItem;

    /**
     * @var ReplyAllToItemType[]
     * @access public
     */
    public $ReplyAllToItem;

    /**
     * @var CancelCalendarItemType[]
     * @access public
     */
    public $CancelCalendarItem;

    /**
     * @var RemoveItemType[]
     * @access public
     */
    public $RemoveItem;

    /**
     * @var SuppressReadReceiptType[]
     * @access public
     */
    public $SuppressReadReceipt;

    /**
     * @var PostReplyItemType[]
     * @access public
     */
    public $PostReplyItem;

    /**
     * @var AcceptSharingInvitationType[]
     * @access public
     */
    public $AcceptSharingInvitation;
}
// @codingStandardsIgnoreEnd
