<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfRestrictedGroupIdentifiersType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfRestrictedGroupIdentifiersType
{
    /**
     * @var SidAndAttributesType[]
     * @access public
     */
    public $RestrictedGroupIdentifier;
}
// @codingStandardsIgnoreEnd
