<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfBaseFolderIdsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfBaseFolderIdsType
{
    /**
     * @var FolderIdType[]
     * @access public
     */
    public $FolderId;

    /**
     * @var DistinguishedFolderIdType[]
     * @access public
     */
    public $DistinguishedFolderId;
}
// @codingStandardsIgnoreEnd
