<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfAttachmentsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfAttachmentsType
{
    /**
     * @var ItemAttachmentType[]
     * @access public
     */
    public $ItemAttachment;

    /**
     * @var FileAttachmentType[]
     * @access public
     */
    public $FileAttachment;
}
// @codingStandardsIgnoreEnd
