<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfItemChangeDescriptionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfItemChangeDescriptionsType
{
    /**
     * @var AppendToItemFieldType[]
     * @access public
     */
    public $AppendToItemField;

    /**
     * @var SetItemFieldType[]
     * @access public
     */
    public $SetItemField;

    /**
     * @var DeleteItemFieldType[]
     * @access public
     */
    public $DeleteItemField;
}
// @codingStandardsIgnoreEnd
