<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfNotificationEventTypesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfNotificationEventTypesType
{
    /**
     * @var string[]
     * @see NotificationEventTypeType
     * @access public
     */
    public $EventType;
}
// @codingStandardsIgnoreEnd
