<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfItemChangesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfItemChangesType
{
    /**
     * @var ItemChangeType[]
     * @access public
     */
    public $ItemChange;
}
// @codingStandardsIgnoreEnd
