<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NotificationEventTypeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NotificationEventTypeType
{
    const COPIED_EVENT = "CopiedEvent";
    const CREATED_EVENT = "CreatedEvent";
    const DELETED_EVENT = "DeletedEvent";
    const MODIFIED_EVENT = "ModifiedEvent";
    const MOVED_EVENT = "MovedEvent";
    const NEW_MAIL_EVENT = "NewMailEvent";
    const FREE_BUSY_CHANGED_EVENT = "FreeBusyChangedEvent";
}
// @codingStandardsIgnoreEnd
