<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * OccurrenceInfoType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class OccurrenceInfoType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $Start;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $End;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $OriginalStart;
}
// @codingStandardsIgnoreEnd
