<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * OpenAsAdminOrSystemServiceType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class OpenAsAdminOrSystemServiceType
{
    /**
     * @var ConnectingSIDType
     * @access public
     */
    public $ConnectingSID;

    /**
     * @var string
     * @see SpecialLogonTypeType
     * @access public
     */
    public $LogonType;
}
// @codingStandardsIgnoreEnd
