<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PathToIndexedFieldType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PathToIndexedFieldType extends BasePathToElementType
{
    /**
     * @var string
     * @see DictionaryURIType
     * @access public
     */
    public $FieldURI;

    /**
     * @var string
     * @access public
     */
    public $FieldIndex;
}
// @codingStandardsIgnoreEnd
