<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * A permission on a folder
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PermissionType extends BasePermissionType
{
    /**
     * @var string
     * @see PermissionReadAccessType
     * @access public
     */
    public $ReadItems;

    /**
     * @var string
     * @see PermissionLevelType
     * @access public
     */
    public $PermissionLevel;
}
// @codingStandardsIgnoreEnd
