<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PermissionLevelType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PermissionLevelType
{
    const NONE = "None";
    const OWNER = "Owner";
    const PUBLISHING_EDITOR = "PublishingEditor";
    const EDITOR = "Editor";
    const PUBLISHING_AUTHOR = "PublishingAuthor";
    const AUTHOR = "Author";
    const NONEDITING_AUTHOR = "NoneditingAuthor";
    const REVIEWER = "Reviewer";
    const CONTRIBUTOR = "Contributor";
    const CUSTOM = "Custom";
}
// @codingStandardsIgnoreEnd
