<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * The set of permissions on a folder
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PermissionSetType
{
    /**
     * @var ArrayOfPermissionsType
     * @access public
     */
    public $Permissions;

    /**
     * @var ArrayOfUnknownEntriesType
     * @access public
     */
    public $UnknownEntries;
}
// @codingStandardsIgnoreEnd
