<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PermissionReadAccessType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PermissionReadAccessType
{
    const NONE = "None";
    const FULL_DETAILS = "FullDetails";
}
// @codingStandardsIgnoreEnd
