<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PhoneCallStateType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PhoneCallStateType
{
    const IDLE = "Idle";
    const CONNECTING = "Connecting";
    const ALERTED = "Alerted";
    const CONNECTED = "Connected";
    const DISCONNECTED = "Disconnected";
    const INCOMING = "Incoming";
    const TRANSFERRING = "Transferring";
    const FORWARDING = "Forwarding";
}
// @codingStandardsIgnoreEnd
