<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PhoneNumberKeyType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PhoneNumberKeyType
{
    const ASSISTANT_PHONE = "AssistantPhone";
    const BUSINESS_FAX = "BusinessFax";
    const BUSINESS_PHONE = "BusinessPhone";
    const BUSINESS_PHONE2 = "BusinessPhone2";
    const CALLBACK = "Callback";
    const CAR_PHONE = "CarPhone";
    const COMPANY_MAIN_PHONE = "CompanyMainPhone";
    const HOME_FAX = "HomeFax";
    const HOME_PHONE = "HomePhone";
    const HOME_PHONE2 = "HomePhone2";
    const ISDN = "Isdn";
    const MOBILE_PHONE = "MobilePhone";
    const OTHER_FAX = "OtherFax";
    const OTHER_TELEPHONE = "OtherTelephone";
    const PAGER = "Pager";
    const PRIMARY_PHONE = "PrimaryPhone";
    const RADIO_PHONE = "RadioPhone";
    const TELEX = "Telex";
    const TTY_TDD_PHONE = "TtyTddPhone";
}
// @codingStandardsIgnoreEnd
