<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PhoneCallInformationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PhoneCallInformationType
{
    /**
     * @var string
     * @see PhoneCallStateType
     * @access public
     */
    public $PhoneCallState;

    /**
     * @var string
     * @see ConnectionFailureCauseType
     * @access public
     */
    public $ConnectionFailureCause;

    /**
     * @var string
     * @access public
     */
    public $SIPResponseText;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $SIPResponseCode;
}
// @codingStandardsIgnoreEnd
