<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PlayOnPhoneType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PlayOnPhoneType extends BaseRequestType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var string
     * @access public
     */
    public $DialString;
}
// @codingStandardsIgnoreEnd
