<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ProtectionRuleSenderDepartmentsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ProtectionRuleSenderDepartmentsType
{
    /**
     * @var string[] WSDL type is ProtectionRuleValueType[]
     * @access public
     */
    public $Value;
}
// @codingStandardsIgnoreEnd
