<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ProtectionRulesServiceConfiguration
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ProtectionRulesServiceConfiguration extends ServiceConfiguration
{
    /**
     * @var ArrayOfProtectionRulesType
     * @access public
     */
    public $Rules;

    /**
     * @var SmtpDomainList
     * @access public
     */
    public $InternalDomains;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $RefreshInterval;
}
// @codingStandardsIgnoreEnd
