<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ProtectionRuleActionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ProtectionRuleActionType
{
    /**
     * @var ProtectionRuleArgumentType[]
     * @access public
     */
    public $Argument;

    /**
     * @var string
     * @see ProtectionRuleActionKindType
     * @access public
     */
    public $Name;
}
// @codingStandardsIgnoreEnd
