<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ProxySecurityContextType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ProxySecurityContextType
{
    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    // @codingStandardsIgnoreStart
    public $_;
    // @codingStandardsIgnoreEnd
}
// @codingStandardsIgnoreEnd
