<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PullSubscriptionRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PullSubscriptionRequestType extends BaseSubscriptionRequestType
{
    /**
     * @var integer WSDL type is SubscriptionTimeoutType
     * @access public
     */
    public $Timeout;
}
// @codingStandardsIgnoreEnd
