<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PushSubscriptionRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PushSubscriptionRequestType extends BaseSubscriptionRequestType
{
    /**
     * @var integer WSDL type is SubscriptionStatusFrequencyType
     * @access public
     */
    public $StatusFrequency;

    /**
     * @var string
     * @access public
     */
    public $URL;
}
// @codingStandardsIgnoreEnd
