<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RecurrenceRangeBaseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RecurrenceRangeBaseType
{
    /**
     * @var string WSDL type is date
     * @access public
     */
    public $StartDate;
}
// @codingStandardsIgnoreEnd
