<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RefreshSharingFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RefreshSharingFolderType extends BaseRequestType
{
    /**
     * @var FolderIdType
     * @access public
     */
    public $SharingFolderId;
}
// @codingStandardsIgnoreEnd
