<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RequestServerVersion
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RequestServerVersion
{
    /**
     * @var string
     * @see ExchangeVersionType
     * @access public
     */
    public $Version;
}
// @codingStandardsIgnoreEnd
