<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ResolveNamesResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ResolveNamesResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfResolutionType
     * @access public
     */
    public $ResolutionSet;
}
// @codingStandardsIgnoreEnd
