<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ResolveNamesSearchScopeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ResolveNamesSearchScopeType
{
    const ACTIVE_DIRECTORY = "ActiveDirectory";
    const ACTIVE_DIRECTORY_CONTACTS = "ActiveDirectoryContacts";
    const CONTACTS = "Contacts";
    const CONTACTS_ACTIVE_DIRECTORY = "ContactsActiveDirectory";
}
// @codingStandardsIgnoreEnd
