<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ResponseClassType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ResponseClassType
{
    const SUCCESS = "Success";
    const WARNING = "Warning";
    const ERROR = "Error";
}
// @codingStandardsIgnoreEnd
