<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ResponseTypeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ResponseTypeType
{
    const UNKNOWN = "Unknown";
    const ORGANIZER = "Organizer";
    const TENTATIVE = "Tentative";
    const ACCEPT = "Accept";
    const DECLINE = "Decline";
    const NO_RESPONSE_RECEIVED = "NoResponseReceived";
}
// @codingStandardsIgnoreEnd
