<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RestrictionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RestrictionType
{
    /**
     * @var ContainsExpressionType[]
     * @access public
     */
    public $Contains;

    /**
     * @var ExcludesType[]
     * @access public
     */
    public $Excludes;

    /**
     * @var ExistsType[]
     * @access public
     */
    public $Exists;

    /**
     * @var IsEqualToType[]
     * @access public
     */
    public $IsEqualTo;

    /**
     * @var IsNotEqualToType[]
     * @access public
     */
    public $IsNotEqualTo;

    /**
     * @var IsGreaterThanType[]
     * @access public
     */
    public $IsGreaterThan;

    /**
     * @var IsGreaterThanOrEqualToType[]
     * @access public
     */
    public $IsGreaterThanOrEqualTo;

    /**
     * @var IsLessThanType[]
     * @access public
     */
    public $IsLessThan;

    /**
     * @var IsLessThanOrEqualToType[]
     * @access public
     */
    public $IsLessThanOrEqualTo;

    /**
     * The name was changed based on a name map provided to the PHP code generation tool
     *
     * @var AndType[]
     * @access public
     */
    public $AndRestriction;

    /**
     * The name was changed based on a name map provided to the PHP code generation tool
     *
     * @var NotType[]
     * @access public
     */
    public $NotRestriction;

    /**
     * The name was changed based on a name map provided to the PHP code generation tool
     *
     * @var OrType[]
     * @access public
     */
    public $OrRestriction;

    private $_parameterMap = array (
        "And" => "AndRestriction",
        "Not" => "NotRestriction",
        "Or" => "OrRestriction",
    );
    /**
     * Provided for getting non-php-standard named variables
     * @param string $var The variable name to get
     * @return mixed The variable value
     */
    public function __get($var)
    {
        return $this->{$this->_parameterMap[$var]};
    }

    /**
     * Provided for setting non-php-standard named variables
     * @param string $var The variable name to set
     * @param mixed $value The value to set
     */
    public function __set($var, $value)
    {
        $this->{$this->_parameterMap[$var]} = $value;
    }
}
// @codingStandardsIgnoreEnd
