<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RuleOperationErrorType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RuleOperationErrorType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $OperationIndex;

    /**
     * @var ArrayOfRuleValidationErrorsType
     * @access public
     */
    public $ValidationErrors;
}
// @codingStandardsIgnoreEnd
