<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents a single validation error on a particular rule property value, predicate property value or action property value
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RuleValidationErrorType
{
    /**
     * @var string
     * @see RuleFieldURIType
     * @access public
     */
    public $FieldURI;

    /**
     * @var string
     * @see RuleValidationErrorCodeType
     * @access public
     */
    public $ErrorCode;

    /**
     * @var string
     * @access public
     */
    public $ErrorMessage;

    /**
     * @var string
     * @access public
     */
    public $FieldValue;
}
// @codingStandardsIgnoreEnd
