<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Rule predicates, used as rule conditions or exceptions
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RulePredicatesType
{
    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Categories;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ContainsBodyStrings;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ContainsHeaderStrings;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ContainsRecipientStrings;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ContainsSenderStrings;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ContainsSubjectOrBodyStrings;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ContainsSubjectStrings;

    /**
     * @var string
     * @see FlaggedForActionType
     * @access public
     */
    public $FlaggedForAction;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $FromAddresses;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $FromConnectedAccounts;

    /**
     * @var boolean
     * @access public
     */
    public $HasAttachments;

    /**
     * @var string
     * @see ImportanceChoicesType
     * @access public
     */
    public $Importance;

    /**
     * @var boolean
     * @access public
     */
    public $IsApprovalRequest;

    /**
     * @var boolean
     * @access public
     */
    public $IsAutomaticForward;

    /**
     * @var boolean
     * @access public
     */
    public $IsAutomaticReply;

    /**
     * @var boolean
     * @access public
     */
    public $IsEncrypted;

    /**
     * @var boolean
     * @access public
     */
    public $IsMeetingRequest;

    /**
     * @var boolean
     * @access public
     */
    public $IsMeetingResponse;

    /**
     * @var boolean
     * @access public
     */
    public $IsNDR;

    /**
     * @var boolean
     * @access public
     */
    public $IsPermissionControlled;

    /**
     * @var boolean
     * @access public
     */
    public $IsReadReceipt;

    /**
     * @var boolean
     * @access public
     */
    public $IsSigned;

    /**
     * @var boolean
     * @access public
     */
    public $IsVoicemail;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $ItemClasses;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $MessageClassifications;

    /**
     * @var boolean
     * @access public
     */
    public $NotSentToMe;

    /**
     * @var boolean
     * @access public
     */
    public $SentCcMe;

    /**
     * @var boolean
     * @access public
     */
    public $SentOnlyToMe;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $SentToAddresses;

    /**
     * @var boolean
     * @access public
     */
    public $SentToMe;

    /**
     * @var boolean
     * @access public
     */
    public $SentToOrCcMe;

    /**
     * @var string
     * @see SensitivityChoicesType
     * @access public
     */
    public $Sensitivity;

    /**
     * @var RulePredicateDateRangeType
     * @access public
     */
    public $WithinDateRange;

    /**
     * @var RulePredicateSizeRangeType
     * @access public
     */
    public $WithinSizeRange;
}
// @codingStandardsIgnoreEnd
