<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Date range type used for the WithinDateRange rule predicate.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RulePredicateDateRangeType
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $StartDateTime;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $EndDateTime;
}
// @codingStandardsIgnoreEnd
