<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Size range type used for the WithinSizeRange rule predicate.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RulePredicateSizeRangeType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MinimumSize;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MaximumSize;
}
// @codingStandardsIgnoreEnd
