<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SearchFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SearchFolderType extends FolderType
{
    /**
     * @var SearchParametersType
     * @access public
     */
    public $SearchParameters;
}
// @codingStandardsIgnoreEnd
