<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SearchParametersType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SearchParametersType
{
    /**
     * @var RestrictionType
     * @access public
     */
    public $Restriction;

    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $BaseFolderIds;

    /**
     * @var string
     * @see SearchFolderTraversalType
     * @access public
     */
    public $Traversal;
}
// @codingStandardsIgnoreEnd
