<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Types of sub-tree traversal for deletion and enumeration
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SearchFolderTraversalType
{
    const SHALLOW = "Shallow";
    const DEEP = "Deep";
}
// @codingStandardsIgnoreEnd
