<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SendNotificationResultType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SendNotificationResultType
{
    /**
     * @var string
     * @see SubscriptionStatusType
     * @access public
     */
    public $SubscriptionStatus;
}
// @codingStandardsIgnoreEnd
