<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SendItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SendItemType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfBaseItemIdsType
     * @access public
     */
    public $ItemIds;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $SavedItemFolderId;

    /**
     * @var boolean
     * @access public
     */
    public $SaveItemToFolder;
}
// @codingStandardsIgnoreEnd
