<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SensitivityChoicesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SensitivityChoicesType
{
    /**
     * The name was changed based on a name map provided to the PHP code generation tool
    */
    const NORMAL_LEVEL = "Normal";
    /**
     * The name was changed based on a name map provided to the PHP code generation tool
    */
    const PERSONAL_LEVEL = "Personal";
    /**
     * The name was changed based on a name map provided to the PHP code generation tool
    */
    const PRIVATE_LEVEL = "Private";
    /**
     * The name was changed based on a name map provided to the PHP code generation tool
    */
    const CONFIDENTIAL_LEVEL = "Confidential";
}
// @codingStandardsIgnoreEnd
