<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SerializedSecurityContextType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SerializedSecurityContextType
{
    /**
     * @var string
     * @access public
     */
    public $UserSid;

    /**
     * @var NonEmptyArrayOfGroupIdentifiersType
     * @access public
     */
    public $GroupSids;

    /**
     * @var NonEmptyArrayOfRestrictedGroupIdentifiersType
     * @access public
     */
    public $RestrictedGroupSids;

    /**
     * @var string
     * @access public
     */
    public $PrimarySmtpAddress;
}
// @codingStandardsIgnoreEnd
