<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ServerVersionInfo
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ServerVersionInfo
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MajorVersion;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MinorVersion;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MajorBuildNumber;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MinorBuildNumber;

    /**
     * @var string
     * @access public
     */
    public $Version;
}
// @codingStandardsIgnoreEnd
