<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ServiceConfigurationResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ServiceConfigurationResponseMessageType extends ResponseMessageType
{
    /**
     * @var MailTipsServiceConfiguration
     * @access public
     */
    public $MailTipsConfiguration;

    /**
     * @var UnifiedMessageServiceConfiguration
     * @access public
     */
    public $UnifiedMessagingConfiguration;

    /**
     * @var ProtectionRulesServiceConfiguration
     * @access public
     */
    public $ProtectionRulesConfiguration;
}
// @codingStandardsIgnoreEnd
