<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SetUserOofSettingsRequest
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SetUserOofSettingsRequest extends BaseRequestType
{
    /**
     * @var EmailAddress
     * @access public
     */
    public $Mailbox;

    /**
     * @var UserOofSettings
     * @access public
     */
    public $UserOofSettings;
}
// @codingStandardsIgnoreEnd
