<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SidAndAttributesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SidAndAttributesType
{
    /**
     * @var string
     * @access public
     */
    public $SecurityIdentifier;

    /**
     * @var integer WSDL type is unsignedInt
     * @access public
     */
    public $Attributes;
}
// @codingStandardsIgnoreEnd
