<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * StreamingSubscriptionRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class StreamingSubscriptionRequestType
{
    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $FolderIds;

    /**
     * @var NonEmptyArrayOfNotificationEventTypesType
     * @access public
     */
    public $EventTypes;

    /**
     * @var boolean
     * @access public
     */
    public $SubscribeToAllFolders;
}
// @codingStandardsIgnoreEnd
