<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SuggestionQuality
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SuggestionQuality
{
    const EXCELLENT = "Excellent";
    const GOOD = "Good";
    const FAIR = "Fair";
    const POOR = "Poor";
}
// @codingStandardsIgnoreEnd
