<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SuggestionDayResult
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SuggestionDayResult
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $Date;

    /**
     * @var string
     * @see SuggestionQuality
     * @access public
     */
    public $DayQuality;

    /**
     * @var ArrayOfSuggestion
     * @access public
     */
    public $SuggestionArray;
}
// @codingStandardsIgnoreEnd
