<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SuggestionsResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SuggestionsResponseType
{
    /**
     * @var ResponseMessageType
     * @access public
     */
    public $ResponseMessage;

    /**
     * @var ArrayOfSuggestionDayResult
     * @access public
     */
    public $SuggestionDayResultArray;
}
// @codingStandardsIgnoreEnd
