<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SyncFolderItemsScopeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SyncFolderItemsScopeType
{
    const NORMAL_ITEMS = "NormalItems";
    const NORMAL_AND_ASSOCIATED_ITEMS = "NormalAndAssociatedItems";
}
// @codingStandardsIgnoreEnd
