<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * TaskDelegateStateType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class TaskDelegateStateType
{
    const NO_MATCH = "NoMatch";
    const OWN_NEW = "OwnNew";
    const OWNED = "Owned";
    const ACCEPTED = "Accepted";
    const DECLINED = "Declined";
    const MAX = "Max";
}
// @codingStandardsIgnoreEnd
