<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * TaskType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class TaskType extends ItemType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $ActualWork;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $AssignedTime;

    /**
     * @var string
     * @access public
     */
    public $BillingInformation;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $ChangeCount;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Companies;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $CompleteDate;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Contacts;

    /**
     * @var string
     * @see TaskDelegateStateType
     * @access public
     */
    public $DelegationState;

    /**
     * @var string
     * @access public
     */
    public $Delegator;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $DueDate;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $IsAssignmentEditable;

    /**
     * @var boolean
     * @access public
     */
    public $IsComplete;

    /**
     * @var boolean
     * @access public
     */
    public $IsRecurring;

    /**
     * @var boolean
     * @access public
     */
    public $IsTeamTask;

    /**
     * @var string
     * @access public
     */
    public $Mileage;

    /**
     * @var string
     * @access public
     */
    public $Owner;

    /**
     * @var double
     * @access public
     */
    public $PercentComplete;

    /**
     * @var TaskRecurrenceType
     * @access public
     */
    public $Recurrence;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $StartDate;

    /**
     * @var string
     * @see TaskStatusType
     * @access public
     */
    public $Status;

    /**
     * @var string
     * @access public
     */
    public $StatusDescription;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $TotalWork;
}
// @codingStandardsIgnoreEnd
