<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * TimeZoneDefinitionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class TimeZoneDefinitionType
{
    /**
     * @var NonEmptyArrayOfPeriodsType
     * @access public
     */
    public $Periods;

    /**
     * @var ArrayOfTransitionsGroupsType
     * @access public
     */
    public $TransitionsGroups;

    /**
     * @var ArrayOfTransitionsType
     * @access public
     */
    public $Transitions;

    /**
     * @var string
     * @access public
     */
    public $Id;

    /**
     * @var string
     * @access public
     */
    public $Name;
}
// @codingStandardsIgnoreEnd
