<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UnifiedMessageServiceConfiguration
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UnifiedMessageServiceConfiguration extends ServiceConfiguration
{
    /**
     * @var boolean
     * @access public
     */
    public $UmEnabled;

    /**
     * @var string
     * @access public
     */
    public $PlayOnPhoneDialString;

    /**
     * @var boolean
     * @access public
     */
    public $PlayOnPhoneEnabled;
}
// @codingStandardsIgnoreEnd
