<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UnsubscribeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UnsubscribeType extends BaseRequestType
{
    /**
     * @var string WSDL type is SubscriptionIdType
     * @access public
     */
    public $SubscriptionId;
}
// @codingStandardsIgnoreEnd
