<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UpdateItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UpdateItemType extends BaseRequestType
{
    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $SavedItemFolderId;

    /**
     * @var NonEmptyArrayOfItemChangesType
     * @access public
     */
    public $ItemChanges;

    /**
     * @var string
     * @see ConflictResolutionType
     * @access public
     */
    public $ConflictResolution;

    /**
     * @var string
     * @see MessageDispositionType
     * @access public
     */
    public $MessageDisposition;

    /**
     * @var string
     * @see CalendarItemUpdateOperationType
     * @access public
     */
    public $SendMeetingInvitationsOrCancellations;
}
// @codingStandardsIgnoreEnd
