<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UpdateInboxRulesRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UpdateInboxRulesRequestType extends BaseRequestType
{
    /**
     * @var string
     * @access public
     */
    public $MailboxSmtpAddress;

    /**
     * @var boolean
     * @access public
     */
    public $RemoveOutlookRuleBlob;

    /**
     * @var ArrayOfRuleOperationsType
     * @access public
     */
    public $Operations;
}
// @codingStandardsIgnoreEnd
