<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UpdateInboxRulesResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UpdateInboxRulesResponseType extends ResponseMessageType
{
    /**
     * @var ArrayOfRuleOperationErrorsType
     * @access public
     */
    public $RuleOperationErrors;
}
// @codingStandardsIgnoreEnd
