<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UploadItemsResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UploadItemsResponseMessageType extends ResponseMessageType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;
}
// @codingStandardsIgnoreEnd
