<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationDictionaryEntryType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationDictionaryEntryType
{
    /**
     * @var UserConfigurationDictionaryObjectType
     * @access public
     */
    public $DictionaryKey;

    /**
     * @var UserConfigurationDictionaryObjectType
     * @access public
     */
    public $DictionaryValue;
}
// @codingStandardsIgnoreEnd
