<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationDictionaryType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationDictionaryType
{
    /**
     * @var UserConfigurationDictionaryEntryType[]
     * @access public
     */
    public $DictionaryEntry;
}
// @codingStandardsIgnoreEnd
