<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationDictionaryObjectType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationDictionaryObjectType
{
    /**
     * @var string
     * @see UserConfigurationDictionaryObjectTypesType
     * @access public
     */
    public $Type;

    /**
     * @var string[]
     * @access public
     */
    public $Value;
}
// @codingStandardsIgnoreEnd
