<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationNameType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationNameType extends TargetFolderIdType
{
    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $Name;
}
// @codingStandardsIgnoreEnd
