<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * WorkingHours
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class WorkingHours
{
    /**
     * @var SerializableTimeZone
     * @access public
     */
    public $TimeZone;

    /**
     * @var ArrayOfWorkingPeriod
     * @access public
     */
    public $WorkingPeriodArray;
}
// @codingStandardsIgnoreEnd
