<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AddDelegateType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AddDelegateType extends BaseDelegateType
{
    /**
     * @var ArrayOfDelegateUserType
     * @access public
     */
    public $DelegateUsers;

    /**
     * @var string
     * @see DeliverMeetingRequestsType
     * @access public
     */
    public $DeliverMeetingRequests;
}
// @codingStandardsIgnoreEnd
