<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents the field of each item to aggregate on and the qualifier to apply to that
 *         field in determining which item will represent the group.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AggregateOnType
{
    /**
     * @var PathToUnindexedFieldType
     * @access public
     */
    public $FieldURI;

    /**
     * @var PathToIndexedFieldType
     * @access public
     */
    public $IndexedFieldURI;

    /**
     * @var PathToExtendedFieldType
     * @access public
     */
    public $ExtendedFieldURI;

    /**
     * @var string
     * @see AggregateType
     * @access public
     */
    public $Aggregate;
}
// @codingStandardsIgnoreEnd
