<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents an alternate mailbox folder or item Id.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AlternateIdType extends AlternateIdBaseType
{
    /**
     * @var string
     * @access public
     */
    public $Id;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $Mailbox;

    /**
     * @var boolean
     * @access public
     */
    public $IsArchive;
}
// @codingStandardsIgnoreEnd
