<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Array of user mailbox.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfUserMailboxesType
{
    /**
     * @var UserMailboxType[]
     * @access public
     */
    public $UserMailbox;
}
// @codingStandardsIgnoreEnd
