<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents an array of rule validation errors
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfRuleValidationErrorsType
{
    /**
     * @var RuleValidationErrorType[]
     * @access public
     */
    public $Error;
}
// @codingStandardsIgnoreEnd
