<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfBinaryType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfBinaryType
{
    /**
     * @var string[] WSDL type is base64Binary[]
     * @access public
     */
    public $Base64Binary;
}
// @codingStandardsIgnoreEnd
