<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AttendeeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AttendeeType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $Mailbox;

    /**
     * @var string
     * @see ResponseTypeType
     * @access public
     */
    public $ResponseType;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $LastResponseTime;
}
// @codingStandardsIgnoreEnd
