<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * BodyTypeResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class BodyTypeResponseType
{
    const BEST = "Best";
    const HTML = "HTML";
    const TEXT = "Text";
}
// @codingStandardsIgnoreEnd
