<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarPermissionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarPermissionType extends BasePermissionType
{
    /**
     * @var string
     * @see CalendarPermissionReadAccessType
     * @access public
     */
    public $ReadItems;

    /**
     * @var string
     * @see CalendarPermissionLevelType
     * @access public
     */
    public $CalendarPermissionLevel;
}
// @codingStandardsIgnoreEnd
