<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarFolderType extends BaseFolderType
{
    /**
     * @var string
     * @see CalendarPermissionReadAccessType
     * @access public
     */
    public $SharingEffectiveRights;

    /**
     * @var CalendarPermissionSetType
     * @access public
     */
    public $PermissionSet;
}
// @codingStandardsIgnoreEnd
