<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ConnectingSIDType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConnectingSIDType
{
    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $PrincipalName;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $SID;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $PrimarySmtpAddress;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $SmtpAddress;
}
// @codingStandardsIgnoreEnd
