<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ContainmentComparisonType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ContainmentComparisonType
{
    const EXACT = "Exact";
    const IGNORE_CASE = "IgnoreCase";
    const IGNORE_NON_SPACING_CHARACTERS = "IgnoreNonSpacingCharacters";
    const LOOSE = "Loose";
    const IGNORE_CASE_AND_NON_SPACING_CHARACTERS = "IgnoreCaseAndNonSpacingCharacters";
    const LOOSE_AND_IGNORE_CASE = "LooseAndIgnoreCase";
    const LOOSE_AND_IGNORE_NON_SPACE = "LooseAndIgnoreNonSpace";
    const LOOSE_AND_IGNORE_CASE_AND_IGNORE_NON_SPACE = "LooseAndIgnoreCaseAndIgnoreNonSpace";
}
// @codingStandardsIgnoreEnd
