<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ConversationActionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConversationActionType
{
    /**
     * @var string
     * @see ConversationActionTypeType
     * @access public
     */
    public $Action;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ConversationId;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $ContextFolderId;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $ConversationLastSyncTime;

    /**
     * @var boolean
     * @access public
     */
    public $ProcessRightAway;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $DestinationFolderId;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Categories;

    /**
     * @var boolean
     * @access public
     */
    public $EnableAlwaysDelete;

    /**
     * @var boolean
     * @access public
     */
    public $IsRead;

    /**
     * @var string
     * @see DisposalType
     * @access public
     */
    public $DeleteType;
}
// @codingStandardsIgnoreEnd
