<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ConversationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConversationType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ConversationId;

    /**
     * @var string
     * @access public
     */
    public $ConversationTopic;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $UniqueRecipients;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $GlobalUniqueRecipients;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $UniqueUnreadSenders;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $GlobalUniqueUnreadSenders;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $UniqueSenders;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $GlobalUniqueSenders;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $LastDeliveryTime;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $GlobalLastDeliveryTime;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Categories;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $GlobalCategories;

    /**
     * @var string
     * @see FlagStatusType
     * @access public
     */
    public $FlagStatus;

    /**
     * @var string
     * @see FlagStatusType
     * @access public
     */
    public $GlobalFlagStatus;

    /**
     * @var boolean
     * @access public
     */
    public $HasAttachments;

    /**
     * @var boolean
     * @access public
     */
    public $GlobalHasAttachments;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MessageCount;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $GlobalMessageCount;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $UnreadCount;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $GlobalUnreadCount;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Size;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $GlobalSize;

    /**
     * @var ArrayOfItemClassType
     * @access public
     */
    public $ItemClasses;

    /**
     * @var ArrayOfItemClassType
     * @access public
     */
    public $GlobalItemClasses;

    /**
     * @var string
     * @see ImportanceChoicesType
     * @access public
     */
    public $Importance;

    /**
     * @var string
     * @see ImportanceChoicesType
     * @access public
     */
    public $GlobalImportance;

    /**
     * @var NonEmptyArrayOfBaseItemIdsType
     * @access public
     */
    public $ItemIds;

    /**
     * @var NonEmptyArrayOfBaseItemIdsType
     * @access public
     */
    public $GlobalItemIds;
}
// @codingStandardsIgnoreEnd
