<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EffectiveRightsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EffectiveRightsType
{
    /**
     * @var boolean
     * @access public
     */
    public $CreateAssociated;

    /**
     * @var boolean
     * @access public
     */
    public $CreateContents;

    /**
     * @var boolean
     * @access public
     */
    public $CreateHierarchy;

    /**
     * @var boolean
     * @access public
     */
    public $Delete;

    /**
     * @var boolean
     * @access public
     */
    public $Modify;

    /**
     * @var boolean
     * @access public
     */
    public $Read;

    /**
     * @var boolean
     * @access public
     */
    public $ViewPrivateItems;
}
// @codingStandardsIgnoreEnd
