<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EmailAddressDictionaryEntryType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EmailAddressDictionaryEntryType
{
    /**
     * @var string
     * @access public
     */
    // @codingStandardsIgnoreStart
    public $_;
    // @codingStandardsIgnoreEnd

    /**
     * @var string
     * @see EmailAddressKeyType
     * @access public
     */
    public $Key;

    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var string
     * @access public
     */
    public $RoutingType;

    /**
     * @var string
     * @see MailboxTypeType
     * @access public
     */
    public $MailboxType;
}
// @codingStandardsIgnoreEnd
