<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EmailAddress
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EmailAddress
{
    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var string
     * @access public
     */
    public $Address;

    /**
     * @var string
     * @access public
     */
    public $RoutingType;
}
// @codingStandardsIgnoreEnd
