<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExternalAudience
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExternalAudience
{
    const NONE = "None";
    const KNOWN = "Known";
    const ALL = "All";
}
// @codingStandardsIgnoreEnd
