<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindConversationResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindConversationResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfConversationsType
     * @access public
     */
    public $Conversations;
}
// @codingStandardsIgnoreEnd
