<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Flagged for action enumeration, currently used in FlaggedForAction rule predicate
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FlaggedForActionType
{
    const ANY = "Any";
    const CALL = "Call";
    const DO_NOT_FORWARD = "DoNotForward";
    const FOLLOW_UP = "FollowUp";
    const FYI = "FYI";
    const FORWARD = "Forward";
    const NO_RESPONSE_NECESSARY = "NoResponseNecessary";
    const READ = "Read";
    const REPLY = "Reply";
    const REPLY_TO_ALL = "ReplyToAll";
    const REVIEW = "Review";
}
// @codingStandardsIgnoreEnd
