<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FolderResponseShapeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FolderResponseShapeType
{
    /**
     * @var string
     * @see DefaultShapeNamesType
     * @access public
     */
    public $BaseShape;

    /**
     * @var NonEmptyArrayOfPathsToElementType
     * @access public
     */
    public $AdditionalProperties;
}
// @codingStandardsIgnoreEnd
