<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetUserAvailabilityResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetUserAvailabilityResponseType
{
    /**
     * @var ArrayOfFreeBusyResponse
     * @access public
     */
    public $FreeBusyResponseArray;

    /**
     * @var SuggestionsResponseType
     * @access public
     */
    public $SuggestionsResponse;
}
// @codingStandardsIgnoreEnd
