<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetUserAvailabilityRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetUserAvailabilityRequestType extends BaseRequestType
{
    /**
     * @var SerializableTimeZone
     * @access public
     */
    public $TimeZone;

    /**
     * @var ArrayOfMailboxData
     * @access public
     */
    public $MailboxDataArray;

    /**
     * @var FreeBusyViewOptionsType
     * @access public
     */
    public $FreeBusyViewOptions;

    /**
     * @var SuggestionsViewOptionsType
     * @access public
     */
    public $SuggestionsViewOptions;
}
// @codingStandardsIgnoreEnd
