<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetUserConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetUserConfigurationType extends BaseRequestType
{
    /**
     * @var UserConfigurationNameType
     * @access public
     */
    public $UserConfigurationName;

    /**
     * @var string
     * @see UserConfigurationPropertyType
     * @access public
     */
    public $UserConfigurationProperties;
}
// @codingStandardsIgnoreEnd
