<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * IndexedPageViewType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class IndexedPageViewType extends BasePagingType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Offset;

    /**
     * @var string
     * @see IndexBasePointType
     * @access public
     */
    public $BasePoint;
}
// @codingStandardsIgnoreEnd
