<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * InternetHeaderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class InternetHeaderType
{
    /**
     * @var string
     * @access public
     */
    // @codingStandardsIgnoreStart
    public $_;
    // @codingStandardsIgnoreEnd

    /**
     * @var string
     * @access public
     */
    public $HeaderName;
}
// @codingStandardsIgnoreEnd
