<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MessageTrackingReportTemplateType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MessageTrackingReportTemplateType
{
    const SUMMARY = "Summary";
    const RECIPIENT_PATH = "RecipientPath";
}
// @codingStandardsIgnoreEnd
