<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MessageType extends ItemType
{
    /**
     * @var SingleRecipientType
     * @access public
     */
    public $Sender;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $ToRecipients;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $CcRecipients;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $BccRecipients;

    /**
     * @var boolean
     * @access public
     */
    public $IsReadReceiptRequested;

    /**
     * @var boolean
     * @access public
     */
    public $IsDeliveryReceiptRequested;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $ConversationIndex;

    /**
     * @var string
     * @access public
     */
    public $ConversationTopic;

    /**
     * @var SingleRecipientType
     * @access public
     */
    public $From;

    /**
     * @var string
     * @access public
     */
    public $InternetMessageId;

    /**
     * @var boolean
     * @access public
     */
    public $IsRead;

    /**
     * @var boolean
     * @access public
     */
    public $IsResponseRequested;

    /**
     * @var string
     * @access public
     */
    public $References;

    /**
     * @var ArrayOfRecipientsType
     * @access public
     */
    public $ReplyTo;

    /**
     * @var SingleRecipientType
     * @access public
     */
    public $ReceivedBy;

    /**
     * @var SingleRecipientType
     * @access public
     */
    public $ReceivedRepresenting;
}
// @codingStandardsIgnoreEnd
