<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfFolderChangeDescriptionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfFolderChangeDescriptionsType
{
    /**
     * @var AppendToFolderFieldType[]
     * @access public
     */
    public $AppendToFolderField;

    /**
     * @var SetFolderFieldType[]
     * @access public
     */
    public $SetFolderField;

    /**
     * @var DeleteFolderFieldType[]
     * @access public
     */
    public $DeleteFolderField;
}
// @codingStandardsIgnoreEnd
