<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * OutOfOfficeMailTip
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class OutOfOfficeMailTip
{
    /**
     * @var ReplyBody
     * @access public
     */
    public $ReplyBody;

    /**
     * @var Duration
     * @access public
     */
    public $Duration;
}
// @codingStandardsIgnoreEnd
