<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PeriodType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PeriodType
{
    /**
     * @var duration
     * @access public
     */
    public $Bias;

    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var string
     * @access public
     */
    public $Id;
}
// @codingStandardsIgnoreEnd
