<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PhysicalAddressIndexType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PhysicalAddressIndexType
{
    const NONE = "None";
    const BUSINESS = "Business";
    const HOME = "Home";
    const OTHER = "Other";
}
// @codingStandardsIgnoreEnd
