<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ProtectionRuleType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ProtectionRuleType
{
    /**
     * @var ProtectionRuleConditionType
     * @access public
     */
    public $Condition;

    /**
     * @var ProtectionRuleActionType
     * @access public
     */
    public $Action;

    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var boolean
     * @access public
     */
    public $UserOverridable;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Priority;
}
// @codingStandardsIgnoreEnd
