<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RecurringMasterItemIdType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RecurringMasterItemIdType extends BaseItemIdType
{
    /**
     * @var string WSDL type is DerivedItemIdType
     * @access public
     */
    public $OccurrenceId;

    /**
     * @var string
     * @access public
     */
    public $ChangeKey;
}
// @codingStandardsIgnoreEnd
