<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ReferenceItemResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ReferenceItemResponseType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ReferenceItemId;

    /**
     * @var string
     * @access public
     */
    public $ObjectName;
}
// @codingStandardsIgnoreEnd
