<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ResponseMessageType
{
    /**
     * @var string
     * @access public
     */
    public $MessageText;

    /**
     * @var string
     * @see ResponseCodeType
     * @access public
     */
    public $ResponseCode;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $DescriptiveLinkKey;

    /**
     * @var MessageXml
     * @access public
     */
    public $MessageXml;

    /**
     * @var string
     * @see ResponseClassType
     * @access public
     */
    public $ResponseClass;
}
// @codingStandardsIgnoreEnd
