<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RootItemIdType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RootItemIdType extends BaseItemIdType
{
    /**
     * @var string
     * @access public
     */
    public $RootItemId;

    /**
     * @var string
     * @access public
     */
    public $RootItemChangeKey;
}
// @codingStandardsIgnoreEnd
