<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SearchItemKindType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SearchItemKindType
{
    const EMAIL = "Email";
    const MEETINGS = "Meetings";
    const TASKS = "Tasks";
    const NOTES = "Notes";
    const DOCS = "Docs";
    const JOURNALS = "Journals";
    const CONTACTS = "Contacts";
    const IM = "Im";
    const VOICEMAIL = "Voicemail";
    const FAXES = "Faxes";
    const POSTS = "Posts";
    const RSSFEEDS = "Rssfeeds";
}
// @codingStandardsIgnoreEnd
