<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SyncFolderItemsChangesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SyncFolderItemsChangesType
{
    /**
     * @var SyncFolderItemsCreateOrUpdateType[]
     * @access public
     */
    public $Create;

    /**
     * @var SyncFolderItemsCreateOrUpdateType[]
     * @access public
     */
    public $Update;

    /**
     * @var SyncFolderItemsDeleteType[]
     * @access public
     */
    public $Delete;

    /**
     * @var SyncFolderItemsReadFlagType[]
     * @access public
     */
    public $ReadFlagChange;
}
// @codingStandardsIgnoreEnd
