<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SyncFolderItemsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SyncFolderItemsType extends BaseRequestType
{
    /**
     * @var ItemResponseShapeType
     * @access public
     */
    public $ItemShape;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $SyncFolderId;

    /**
     * @var string
     * @access public
     */
    public $SyncState;

    /**
     * @var ArrayOfBaseItemIdsType
     * @access public
     */
    public $Ignore;

    /**
     * @var integer WSDL type is MaxSyncChangesReturnedType
     * @access public
     */
    public $MaxChangesReturned;

    /**
     * @var string
     * @see SyncFolderItemsScopeType
     * @access public
     */
    public $SyncScope;
}
// @codingStandardsIgnoreEnd
