<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * TaskStatusType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class TaskStatusType
{
    const NOT_STARTED = "NotStarted";
    const IN_PROGRESS = "InProgress";
    const COMPLETED = "Completed";
    const WAITING_ON_OTHERS = "WaitingOnOthers";
    const DEFERRED = "Deferred";
}
// @codingStandardsIgnoreEnd
