<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationDictionaryObjectTypesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationDictionaryObjectTypesType
{
    const DATE_TIME = "DateTime";
    const BOOLEAN = "Boolean";
    const BYTE = "Byte";
    const STRING = "String";
    const INTEGER32 = "Integer32";
    const UNSIGNED_INTEGER32 = "UnsignedInteger32";
    const INTEGER64 = "Integer64";
    const UNSIGNED_INTEGER64 = "UnsignedInteger64";
    const STRING_ARRAY = "StringArray";
    const BYTE_ARRAY = "ByteArray";
}
// @codingStandardsIgnoreEnd
