<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationPropertyType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationPropertyType
{
    const ID = "Id";
    const DICTIONARY = "Dictionary";
    const XML_DATA = "XmlData";
    const BINARY_DATA = "BinaryData";
    const ALL = "All";
}
// @codingStandardsIgnoreEnd
