<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserConfigurationType
{
    /**
     * @var UserConfigurationNameType
     * @access public
     */
    public $UserConfigurationName;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var UserConfigurationDictionaryType
     * @access public
     */
    public $Dictionary;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $XmlData;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $BinaryData;
}
// @codingStandardsIgnoreEnd
