<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AbsoluteYearlyRecurrencePatternType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AbsoluteYearlyRecurrencePatternType extends RecurrencePatternBaseType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $DayOfMonth;

    /**
     * @var string
     * @see MonthNamesType
     * @access public
     */
    public $Month;
}
// @codingStandardsIgnoreEnd
