<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents an alternate public folder item Id.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AlternatePublicFolderItemIdType extends AlternatePublicFolderIdType
{
    /**
     * @var string
     * @access public
     */
    public $ItemId;
}
// @codingStandardsIgnoreEnd
