<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ApplyConversationActionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ApplyConversationActionType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfApplyConversationActionType
     * @access public
     */
    public $ConversationActions;
}
// @codingStandardsIgnoreEnd
