<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfTransitionsGroupsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfTransitionsGroupsType
{
    /**
     * @var ArrayOfTransitionsType[]
     * @access public
     */
    public $TransitionsGroup;
}
// @codingStandardsIgnoreEnd
