<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ArrayOfWorkingPeriod
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfWorkingPeriod
{
    /**
     * @var WorkingPeriod[]
     * @access public
     */
    public $WorkingPeriod;
}
// @codingStandardsIgnoreEnd
