<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents an array of rule operations to be performed
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ArrayOfRuleOperationsType
{
    /**
     * @var CreateRuleOperationType[]
     * @access public
     */
    public $CreateRuleOperation;

    /**
     * @var SetRuleOperationType[]
     * @access public
     */
    public $SetRuleOperation;

    /**
     * @var DeleteRuleOperationType[]
     * @access public
     */
    public $DeleteRuleOperation;
}
// @codingStandardsIgnoreEnd
