<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * AttachmentType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class AttachmentType
{
    /**
     * @var AttachmentIdType
     * @access public
     */
    public $AttachmentId;

    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var string
     * @access public
     */
    public $ContentType;

    /**
     * @var string
     * @access public
     */
    public $ContentId;

    /**
     * @var string
     * @access public
     */
    public $ContentLocation;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Size;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $LastModifiedTime;

    /**
     * @var boolean
     * @access public
     */
    public $IsInline;
}
// @codingStandardsIgnoreEnd
