<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * BaseSubscriptionRequestType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class BaseSubscriptionRequestType
{
    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $FolderIds;

    /**
     * @var NonEmptyArrayOfNotificationEventTypesType
     * @access public
     */
    public $EventTypes;

    /**
     * @var string WSDL type is WatermarkType
     * @access public
     */
    public $Watermark;

    /**
     * @var boolean
     * @access public
     */
    public $SubscribeToAllFolders;
}
// @codingStandardsIgnoreEnd
