<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * BaseDelegateResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class BaseDelegateResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfDelegateUserResponseMessageType
     * @access public
     */
    public $ResponseMessages;
}
// @codingStandardsIgnoreEnd
