<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * A permission on a folder
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class BasePermissionType
{
    /**
     * @var UserIdType
     * @access public
     */
    public $UserId;

    /**
     * @var boolean
     * @access public
     */
    public $CanCreateItems;

    /**
     * @var boolean
     * @access public
     */
    public $CanCreateSubFolders;

    /**
     * @var boolean
     * @access public
     */
    public $IsFolderOwner;

    /**
     * @var boolean
     * @access public
     */
    public $IsFolderVisible;

    /**
     * @var boolean
     * @access public
     */
    public $IsFolderContact;

    /**
     * @var string
     * @see PermissionActionType
     * @access public
     */
    public $EditItems;

    /**
     * @var string
     * @see PermissionActionType
     * @access public
     */
    public $DeleteItems;
}
// @codingStandardsIgnoreEnd
