<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarItemUpdateOperationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarItemUpdateOperationType
{
    const SEND_TO_NONE = "SendToNone";
    const SEND_ONLY_TO_ALL = "SendOnlyToAll";
    const SEND_ONLY_TO_CHANGED = "SendOnlyToChanged";
    const SEND_TO_ALL_AND_SAVE_COPY = "SendToAllAndSaveCopy";
    const SEND_TO_CHANGED_AND_SAVE_COPY = "SendToChangedAndSaveCopy";
}
// @codingStandardsIgnoreEnd
