<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarItemTypeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarItemTypeType
{
    const SINGLE = "Single";
    const OCCURRENCE = "Occurrence";
    const EXCEPTION = "Exception";
    const RECURRING_MASTER = "RecurringMaster";
}
// @codingStandardsIgnoreEnd
