<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CalendarPermissionLevelType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CalendarPermissionLevelType
{
    const NONE = "None";
    const OWNER = "Owner";
    const PUBLISHING_EDITOR = "PublishingEditor";
    const EDITOR = "Editor";
    const PUBLISHING_AUTHOR = "PublishingAuthor";
    const AUTHOR = "Author";
    const NONEDITING_AUTHOR = "NoneditingAuthor";
    const REVIEWER = "Reviewer";
    const CONTRIBUTOR = "Contributor";
    const FREE_BUSY_TIME_ONLY = "FreeBusyTimeOnly";
    const FREE_BUSY_TIME_AND_SUBJECT_AND_LOCATION = "FreeBusyTimeAndSubjectAndLocation";
    const CUSTOM = "Custom";
}
// @codingStandardsIgnoreEnd
