<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CompleteNameType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CompleteNameType
{
    /**
     * @var string
     * @access public
     */
    public $Title;

    /**
     * @var string
     * @access public
     */
    public $FirstName;

    /**
     * @var string
     * @access public
     */
    public $MiddleName;

    /**
     * @var string
     * @access public
     */
    public $LastName;

    /**
     * @var string
     * @access public
     */
    public $Suffix;

    /**
     * @var string
     * @access public
     */
    public $Initials;

    /**
     * @var string
     * @access public
     */
    public $FullName;

    /**
     * @var string
     * @access public
     */
    public $Nickname;

    /**
     * @var string
     * @access public
     */
    public $YomiFirstName;

    /**
     * @var string
     * @access public
     */
    public $YomiLastName;
}
// @codingStandardsIgnoreEnd
