<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ConnectionFailureCauseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConnectionFailureCauseType
{
    const NONE = "None";
    const USER_BUSY = "UserBusy";
    const NO_ANSWER = "NoAnswer";
    const UNAVAILABLE = "Unavailable";
    const OTHER = "Other";
}
// @codingStandardsIgnoreEnd
