<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ContactSourceType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ContactSourceType
{
    const ACTIVE_DIRECTORY = "ActiveDirectory";
    const STORE = "Store";
}
// @codingStandardsIgnoreEnd
