<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Response Message for a single id conversion in the ConvertId web method.  Note
 *                 that the AlternateId element will be missing in the case of an error.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ConvertIdResponseMessageType extends ResponseMessageType
{
    /**
     * @var AlternateIdBaseType
     * @access public
     */
    public $AlternateId;
}
// @codingStandardsIgnoreEnd
