<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CreateItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CreateItemType extends BaseRequestType
{
    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $SavedItemFolderId;

    /**
     * @var NonEmptyArrayOfAllItemsType
     * @access public
     */
    public $Items;

    /**
     * @var string
     * @see MessageDispositionType
     * @access public
     */
    public $MessageDisposition;

    /**
     * @var string
     * @see CalendarItemCreateOrDeleteOperationType
     * @access public
     */
    public $SendMeetingInvitations;
}
// @codingStandardsIgnoreEnd
