<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CreateAttachmentType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CreateAttachmentType extends BaseRequestType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ParentItemId;

    /**
     * @var NonEmptyArrayOfAttachmentsType
     * @access public
     */
    public $Attachments;
}
// @codingStandardsIgnoreEnd
