<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * CreateActionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class CreateActionType
{
    const CREATE_NEW = "CreateNew";
    const UPDATE = "Update";
    const UPDATE_OR_CREATE = "UpdateOrCreate";
}
// @codingStandardsIgnoreEnd
