<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DeleteAttachmentType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DeleteAttachmentType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfRequestAttachmentIdsType
     * @access public
     */
    public $AttachmentIds;
}
// @codingStandardsIgnoreEnd
