<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DeletedOccurrenceInfoType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DeletedOccurrenceInfoType
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $Start;
}
// @codingStandardsIgnoreEnd
