<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DictionaryURIType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DictionaryURIType
{
    const ITEM_INTERNET_MESSAGE_HEADER = "item:InternetMessageHeader";
    const CONTACTS_IM_ADDRESS = "contacts:ImAddress";
    const CONTACTS_PHYSICAL_ADDRESS_STREET = "contacts:PhysicalAddress:Street";
    const CONTACTS_PHYSICAL_ADDRESS_CITY = "contacts:PhysicalAddress:City";
    const CONTACTS_PHYSICAL_ADDRESS_STATE = "contacts:PhysicalAddress:State";
    const CONTACTS_PHYSICAL_ADDRESS_COUNTRY_OR_REGION = "contacts:PhysicalAddress:CountryOrRegion";
    const CONTACTS_PHYSICAL_ADDRESS_POSTAL_CODE = "contacts:PhysicalAddress:PostalCode";
    const CONTACTS_PHONE_NUMBER = "contacts:PhoneNumber";
    const CONTACTS_EMAIL_ADDRESS = "contacts:EmailAddress";
    const DISTRIBUTIONLIST_MEMBERS_MEMBER = "distributionlist:Members:Member";
}
// @codingStandardsIgnoreEnd
