<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DisposalType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DisposalType
{
    const HARD_DELETE = "HardDelete";
    const SOFT_DELETE = "SoftDelete";
    const MOVE_TO_DELETED_ITEMS = "MoveToDeletedItems";
}
// @codingStandardsIgnoreEnd
