<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Allows consumers to access standard groupings for FindItem queries.  This is in
 *         contrast to the arbitrary (custom) groupings available via the t:GroupByType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DistinguishedGroupByType extends BaseGroupByType
{
    /**
     * @var string
     * @see StandardGroupByType
     * @access public
     */
    public $StandardGroupBy;
}
// @codingStandardsIgnoreEnd
