<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * DistinguishedUserType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DistinguishedUserType
{
    /**
     * The name was changed based on a name map provided to the PHP code generation tool
    */
    const DEFAULT_USER = "Default";
    const ANONYMOUS = "Anonymous";
}
// @codingStandardsIgnoreEnd
