<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * URIs for the distinguished folders accessible from a mailbox
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class DistinguishedFolderIdNameType
{
    const CALENDAR = "calendar";
    const CONTACTS = "contacts";
    const DELETEDITEMS = "deleteditems";
    const DRAFTS = "drafts";
    const INBOX = "inbox";
    const JOURNAL = "journal";
    const NOTES = "notes";
    const OUTBOX = "outbox";
    const SENTITEMS = "sentitems";
    const TASKS = "tasks";
    const MSGFOLDERROOT = "msgfolderroot";
    const PUBLICFOLDERSROOT = "publicfoldersroot";
    const ROOT = "root";
    const JUNKEMAIL = "junkemail";
    const SEARCHFOLDERS = "searchfolders";
    const VOICEMAIL = "voicemail";
    const RECOVERABLEITEMSROOT = "recoverableitemsroot";
    const RECOVERABLEITEMSDELETIONS = "recoverableitemsdeletions";
    const RECOVERABLEITEMSVERSIONS = "recoverableitemsversions";
    const RECOVERABLEITEMSPURGES = "recoverableitemspurges";
    const ARCHIVEROOT = "archiveroot";
    const ARCHIVEMSGFOLDERROOT = "archivemsgfolderroot";
    const ARCHIVEDELETEDITEMS = "archivedeleteditems";
    const ARCHIVERECOVERABLEITEMSROOT = "archiverecoverableitemsroot";
    const ARCHIVERECOVERABLEITEMSDELETIONS = "archiverecoverableitemsdeletions";
    const ARCHIVERECOVERABLEITEMSVERSIONS = "archiverecoverableitemsversions";
    const ARCHIVERECOVERABLEITEMSPURGES = "archiverecoverableitemspurges";
}
// @codingStandardsIgnoreEnd
