<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EmailAddressKeyType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EmailAddressKeyType
{
    const EMAIL_ADDRESS1 = "EmailAddress1";
    const EMAIL_ADDRESS2 = "EmailAddress2";
    const EMAIL_ADDRESS3 = "EmailAddress3";
}
// @codingStandardsIgnoreEnd
