<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EmptyFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EmptyFolderType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $FolderIds;

    /**
     * @var string
     * @see DisposalType
     * @access public
     */
    public $DeleteType;

    /**
     * @var boolean
     * @access public
     */
    public $DeleteSubFolders;
}
// @codingStandardsIgnoreEnd
