<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * EndDateRecurrenceRangeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class EndDateRecurrenceRangeType extends RecurrenceRangeBaseType
{
    /**
     * @var string WSDL type is date
     * @access public
     */
    public $EndDate;
}
// @codingStandardsIgnoreEnd
