<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExportItemsResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExportItemsResponseMessageType extends ResponseMessageType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $Data;
}
// @codingStandardsIgnoreEnd
