<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ExportItemsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ExportItemsType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfItemIdsType
     * @access public
     */
    public $ItemIds;
}
// @codingStandardsIgnoreEnd
