<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FileAttachmentType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FileAttachmentType extends AttachmentType
{
    /**
     * @var boolean
     * @access public
     */
    public $IsContactPhoto;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $Content;
}
// @codingStandardsIgnoreEnd
