<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindItemParentType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindItemParentType
{
    /**
     * @var ArrayOfRealItemsType
     * @access public
     */
    public $Items;

    /**
     * @var ArrayOfGroupedItemsType
     * @access public
     */
    public $Groups;
}
// @codingStandardsIgnoreEnd
