<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindMessageTrackingReportResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindMessageTrackingReportResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Diagnostics;

    /**
     * @var ArrayOfFindMessageTrackingSearchResultType
     * @access public
     */
    public $MessageTrackingSearchResults;

    /**
     * @var string
     * @access public
     */
    public $ExecutedSearchScope;

    /**
     * @var ArrayOfArraysOfTrackingPropertiesType
     * @access public
     */
    public $Errors;

    /**
     * @var ArrayOfTrackingPropertiesType
     * @access public
     */
    public $Properties;
}
// @codingStandardsIgnoreEnd
