<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FindFolderType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FindFolderType extends BaseRequestType
{
    /**
     * @var FolderResponseShapeType
     * @access public
     */
    public $FolderShape;

    /**
     * @var IndexedPageViewType
     * @access public
     */
    public $IndexedPageFolderView;

    /**
     * @var FractionalPageViewType
     * @access public
     */
    public $FractionalPageFolderView;

    /**
     * @var RestrictionType
     * @access public
     */
    public $Restriction;

    /**
     * @var NonEmptyArrayOfBaseFolderIdsType
     * @access public
     */
    public $ParentFolderIds;

    /**
     * @var string
     * @see FolderQueryTraversalType
     * @access public
     */
    public $Traversal;
}
// @codingStandardsIgnoreEnd
