<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FreeBusyView
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FreeBusyView
{
    /**
     * @var string
     * @see FreeBusyViewType
     * @access public
     */
    public $FreeBusyViewType;

    /**
     * @var string
     * @access public
     */
    public $MergedFreeBusy;

    /**
     * @var ArrayOfCalendarEvent
     * @access public
     */
    public $CalendarEventArray;

    /**
     * @var WorkingHours
     * @access public
     */
    public $WorkingHours;
}
// @codingStandardsIgnoreEnd
