<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FreeBusyViewType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FreeBusyViewType
{
    const NONE = "None";
    const MERGED_ONLY = "MergedOnly";
    const FREE_BUSY = "FreeBusy";
    const FREE_BUSY_MERGED = "FreeBusyMerged";
    const DETAILED = "Detailed";
    const DETAILED_MERGED = "DetailedMerged";
}
// @codingStandardsIgnoreEnd
