<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * FreeBusyResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class FreeBusyResponseType
{
    /**
     * @var ResponseMessageType
     * @access public
     */
    public $ResponseMessage;

    /**
     * @var FreeBusyView
     * @access public
     */
    public $FreeBusyView;
}
// @codingStandardsIgnoreEnd
