<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetInboxRulesResponseType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetInboxRulesResponseType extends ResponseMessageType
{
    /**
     * @var boolean
     * @access public
     */
    public $OutlookRuleBlobExists;

    /**
     * @var ArrayOfRulesType
     * @access public
     */
    public $InboxRules;
}
// @codingStandardsIgnoreEnd
