<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetMessageTrackingReportResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetMessageTrackingReportResponseMessageType extends ResponseMessageType
{
    /**
     * @var MessageTrackingReportType
     * @access public
     */
    public $MessageTrackingReport;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $Diagnostics;

    /**
     * @var ArrayOfArraysOfTrackingPropertiesType
     * @access public
     */
    public $Errors;

    /**
     * @var ArrayOfTrackingPropertiesType
     * @access public
     */
    public $Properties;
}
// @codingStandardsIgnoreEnd
