<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetPhoneCallInformationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetPhoneCallInformationType extends BaseRequestType
{
    /**
     * @var PhoneCallIdType
     * @access public
     */
    public $PhoneCallId;
}
// @codingStandardsIgnoreEnd
