<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetRoomsResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetRoomsResponseMessageType extends ResponseMessageType
{
    /**
     * @var ArrayOfRoomsType
     * @access public
     */
    public $Rooms;
}
// @codingStandardsIgnoreEnd
