<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetStreamingEventsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetStreamingEventsType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfSubscriptionIdsType
     * @access public
     */
    public $SubscriptionIds;

    /**
     * @var integer WSDL type is StreamingSubscriptionConnectionTimeoutType
     * @access public
     */
    public $ConnectionTimeout;
}
// @codingStandardsIgnoreEnd
