<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetSharingMetadataType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetSharingMetadataType extends BaseRequestType
{
    /**
     * @var FolderIdType
     * @access public
     */
    public $IdOfFolderToShare;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $SenderSmtpAddress;

    /**
     * @var ArrayOfSmtpAddressType
     * @access public
     */
    public $Recipients;
}
// @codingStandardsIgnoreEnd
