<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetServiceConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetServiceConfigurationType extends BaseRequestType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $ActingAs;

    /**
     * @var ArrayOfServiceConfigurationType
     * @access public
     */
    public $RequestedConfiguration;
}
// @codingStandardsIgnoreEnd
