<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GetUserOofSettingsResponse
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GetUserOofSettingsResponse
{
    /**
     * @var ResponseMessageType
     * @access public
     */
    public $ResponseMessage;

    /**
     * @var UserOofSettings
     * @access public
     */
    public $OofSettings;

    /**
     * @var string
     * @see ExternalAudience
     * @access public
     */
    public $AllowExternalOof;
}
// @codingStandardsIgnoreEnd
