<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * GroupedItemsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class GroupedItemsType
{
    /**
     * @var string
     * @access public
     */
    public $GroupIndex;

    /**
     * @var ArrayOfRealItemsType
     * @access public
     */
    public $Items;
}
// @codingStandardsIgnoreEnd
