<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Identifier for a fully resolved item
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ItemIdType extends BaseItemIdType
{
    /**
     * @var string
     * @access public
     */
    public $Id;

    /**
     * @var string
     * @access public
     */
    public $ChangeKey;
}
// @codingStandardsIgnoreEnd
