<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Keyword statistics search result.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class KeywordStatisticsSearchResultType
{
    /**
     * @var string
     * @access public
     */
    public $Keyword;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $ItemHits;

    /**
     * @var integer WSDL type is long
     * @access public
     */
    public $Size;
}
// @codingStandardsIgnoreEnd
