<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MailTips
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MailTips
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $RecipientAddress;

    /**
     * @var string
     * @see MailTipTypes
     * @access public
     */
    public $PendingMailTips;

    /**
     * @var OutOfOfficeMailTip
     * @access public
     */
    public $OutOfOffice;

    /**
     * @var boolean
     * @access public
     */
    public $MailboxFull;

    /**
     * @var string
     * @access public
     */
    public $CustomMailTip;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $TotalMemberCount;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $ExternalMemberCount;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MaxMessageSize;

    /**
     * @var boolean
     * @access public
     */
    public $DeliveryRestricted;

    /**
     * @var boolean
     * @access public
     */
    public $IsModerated;

    /**
     * @var boolean
     * @access public
     */
    public $InvalidRecipient;
}
// @codingStandardsIgnoreEnd
