<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MailboxTypeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MailboxTypeType
{
    const UNKNOWN = "Unknown";
    const ONE_OFF = "OneOff";
    const MAILBOX = "Mailbox";
    const PUBLIC_DL = "PublicDL";
    const PRIVATE_DL = "PrivateDL";
    const CONTACT = "Contact";
    const PUBLIC_FOLDER = "PublicFolder";
}
// @codingStandardsIgnoreEnd
