<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MailTipsServiceConfiguration
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MailTipsServiceConfiguration extends ServiceConfiguration
{
    /**
     * @var boolean
     * @access public
     */
    public $MailTipsEnabled;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MaxRecipientsPerGetMailTipsRequest;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MaxMessageSize;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $LargeAudienceThreshold;

    /**
     * @var boolean
     * @access public
     */
    public $ShowExternalRecipientCount;

    /**
     * @var SmtpDomainList
     * @access public
     */
    public $InternalDomains;
}
// @codingStandardsIgnoreEnd
