<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MeetingMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MeetingMessageType extends MessageType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $AssociatedCalendarItemId;

    /**
     * @var boolean
     * @access public
     */
    public $IsDelegated;

    /**
     * @var boolean
     * @access public
     */
    public $IsOutOfDate;

    /**
     * @var boolean
     * @access public
     */
    public $HasBeenProcessed;

    /**
     * @var string
     * @see ResponseTypeType
     * @access public
     */
    public $ResponseType;

    /**
     * @var string
     * @access public
     */
    public $UID;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $RecurrenceId;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $DateTimeStamp;
}
// @codingStandardsIgnoreEnd
