<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MeetingAttendeeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MeetingAttendeeType
{
    const ORGANIZER = "Organizer";
    const REQUIRED = "Required";
    const OPTIONAL = "Optional";
    const ROOM = "Room";
    const RESOURCE = "Resource";
}
// @codingStandardsIgnoreEnd
