<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MeetingRequestTypeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MeetingRequestTypeType
{
    const NONE = "None";
    const FULL_UPDATE = "FullUpdate";
    const INFORMATIONAL_UPDATE = "InformationalUpdate";
    const NEW_MEETING_REQUEST = "NewMeetingRequest";
    const OUTDATED = "Outdated";
    const SILENT_UPDATE = "SilentUpdate";
    const PRINCIPAL_WANTS_COPY = "PrincipalWantsCopy";
}
// @codingStandardsIgnoreEnd
