<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MemberType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MemberType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $Mailbox;

    /**
     * @var string
     * @see MemberStatusType
     * @access public
     */
    public $Status;

    /**
     * @var string
     * @access public
     */
    public $Key;
}
// @codingStandardsIgnoreEnd
