<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MemberStatusType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MemberStatusType
{
    const UNRECOGNIZED = "Unrecognized";
    const NORMAL = "Normal";
    const DEMOTED = "Demoted";
}
// @codingStandardsIgnoreEnd
