<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MessageTrackingReportType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MessageTrackingReportType
{
    /**
     * @var EmailAddressType
     * @access public
     */
    public $Sender;

    /**
     * @var EmailAddressType
     * @access public
     */
    public $PurportedSender;

    /**
     * @var string
     * @access public
     */
    public $Subject;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $SubmitTime;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $OriginalRecipients;

    /**
     * @var ArrayOfRecipientTrackingEventType
     * @access public
     */
    public $RecipientTrackingEvents;

    /**
     * @var ArrayOfTrackingPropertiesType
     * @access public
     */
    public $Properties;
}
// @codingStandardsIgnoreEnd
