<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ModifiedEventType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ModifiedEventType extends BaseObjectChangedEventType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $UnreadCount;
}
// @codingStandardsIgnoreEnd
