<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * MovedCopiedEventType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class MovedCopiedEventType extends BaseObjectChangedEventType
{
    /**
     * @var FolderIdType
     * @access public
     */
    public $OldFolderId;

    /**
     * @var ItemIdType
     * @access public
     */
    public $OldItemId;

    /**
     * @var FolderIdType
     * @access public
     */
    public $OldParentFolderId;
}
// @codingStandardsIgnoreEnd
