<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfBaseItemIdsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfBaseItemIdsType
{
    /**
     * @var ItemIdType[]
     * @access public
     */
    public $ItemId;

    /**
     * @var OccurrenceItemIdType[]
     * @access public
     */
    public $OccurrenceItemId;

    /**
     * @var RecurringMasterItemIdType[]
     * @access public
     */
    public $RecurringMasterItemId;
}
// @codingStandardsIgnoreEnd
