<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NonEmptyArrayOfAllItemsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NonEmptyArrayOfAllItemsType
{
    /**
     * @var ItemType[]
     * @access public
     */
    public $Item;

    /**
     * @var MessageType[]
     * @access public
     */
    public $Message;

    /**
     * @var CalendarItemType[]
     * @access public
     */
    public $CalendarItem;

    /**
     * @var ContactItemType[]
     * @access public
     */
    public $Contact;

    /**
     * @var DistributionListType[]
     * @access public
     */
    public $DistributionList;

    /**
     * @var MeetingMessageType[]
     * @access public
     */
    public $MeetingMessage;

    /**
     * @var MeetingRequestMessageType[]
     * @access public
     */
    public $MeetingRequest;

    /**
     * @var MeetingResponseMessageType[]
     * @access public
     */
    public $MeetingResponse;

    /**
     * @var MeetingCancellationMessageType[]
     * @access public
     */
    public $MeetingCancellation;

    /**
     * @var TaskType[]
     * @access public
     */
    public $Task;

    /**
     * @var PostItemType[]
     * @access public
     */
    public $PostItem;

    /**
     * @var ReplyToItemType[]
     * @access public
     */
    public $ReplyToItem;

    /**
     * @var ForwardItemType[]
     * @access public
     */
    public $ForwardItem;

    /**
     * @var ReplyAllToItemType[]
     * @access public
     */
    public $ReplyAllToItem;

    /**
     * @var AcceptItemType[]
     * @access public
     */
    public $AcceptItem;

    /**
     * @var TentativelyAcceptItemType[]
     * @access public
     */
    public $TentativelyAcceptItem;

    /**
     * @var DeclineItemType[]
     * @access public
     */
    public $DeclineItem;

    /**
     * @var CancelCalendarItemType[]
     * @access public
     */
    public $CancelCalendarItem;

    /**
     * @var RemoveItemType[]
     * @access public
     */
    public $RemoveItem;

    /**
     * @var SuppressReadReceiptType[]
     * @access public
     */
    public $SuppressReadReceipt;

    /**
     * @var PostReplyItemType[]
     * @access public
     */
    public $PostReplyItem;

    /**
     * @var AcceptSharingInvitationType[]
     * @access public
     */
    public $AcceptSharingInvitation;
}
// @codingStandardsIgnoreEnd
