<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * NotificationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class NotificationType
{
    /**
     * @var string WSDL type is SubscriptionIdType
     * @access public
     */
    public $SubscriptionId;

    /**
     * @var string WSDL type is WatermarkType
     * @access public
     */
    public $PreviousWatermark;

    /**
     * @var boolean
     * @access public
     */
    public $MoreEvents;

    /**
     * @var MovedCopiedEventType[]
     * @access public
     */
    public $CopiedEvent;

    /**
     * @var BaseObjectChangedEventType[]
     * @access public
     */
    public $CreatedEvent;

    /**
     * @var BaseObjectChangedEventType[]
     * @access public
     */
    public $DeletedEvent;

    /**
     * @var ModifiedEventType[]
     * @access public
     */
    public $ModifiedEvent;

    /**
     * @var MovedCopiedEventType[]
     * @access public
     */
    public $MovedEvent;

    /**
     * @var BaseObjectChangedEventType[]
     * @access public
     */
    public $NewMailEvent;

    /**
     * @var BaseNotificationEventType[]
     * @access public
     */
    public $StatusEvent;

    /**
     * @var BaseObjectChangedEventType[]
     * @access public
     */
    public $FreeBusyChangedEvent;
}
// @codingStandardsIgnoreEnd
