<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * OccurrenceItemIdType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class OccurrenceItemIdType extends BaseItemIdType
{
    /**
     * @var string WSDL type is DerivedItemIdType
     * @access public
     */
    public $RecurringMasterId;

    /**
     * @var string
     * @access public
     */
    public $ChangeKey;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $InstanceIndex;
}
// @codingStandardsIgnoreEnd
