<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents an extended property.  Note that there are only a couple of valid attribute
 *         combinations.  Note that all occurances require the PropertyType attribute.
 *
 *         1.  (DistinguishedPropertySetId || PropertySetId) + (PropertyName || Property Id)
 *         2.  PropertyTag
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PathToExtendedFieldType extends BasePathToElementType
{
    /**
     * @var string
     * @see DistinguishedPropertySetType
     * @access public
     */
    public $DistinguishedPropertySetId;

    /**
     * @var string WSDL type is GuidType
     * @access public
     */
    public $PropertySetId;

    /**
     * @var string WSDL type is PropertyTagType
     * @access public
     */
    public $PropertyTag;

    /**
     * @var string
     * @access public
     */
    public $PropertyName;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $PropertyId;

    /**
     * @var string
     * @see MapiPropertyTypeType
     * @access public
     */
    public $PropertyType;
}
// @codingStandardsIgnoreEnd
