<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PathToExceptionFieldType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PathToExceptionFieldType extends BasePathToElementType
{
    /**
     * @var string
     * @see ExceptionPropertyURIType
     * @access public
     */
    public $FieldURI;
}
// @codingStandardsIgnoreEnd
