<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PathToUnindexedFieldType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PathToUnindexedFieldType extends BasePathToElementType
{
    /**
     * @var string
     * @see UnindexedFieldURIType
     * @access public
     */
    public $FieldURI;
}
// @codingStandardsIgnoreEnd
