<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PhysicalAddressDictionaryEntryType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PhysicalAddressDictionaryEntryType
{
    /**
     * @var string
     * @access public
     */
    public $Street;

    /**
     * @var string
     * @access public
     */
    public $City;

    /**
     * @var string
     * @access public
     */
    public $State;

    /**
     * @var string
     * @access public
     */
    public $CountryOrRegion;

    /**
     * @var string
     * @access public
     */
    public $PostalCode;

    /**
     * @var string
     * @see PhysicalAddressKeyType
     * @access public
     */
    public $Key;
}
// @codingStandardsIgnoreEnd
