<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PhysicalAddressDictionaryType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PhysicalAddressDictionaryType
{
    /**
     * @var PhysicalAddressDictionaryEntryType[]
     * @access public
     */
    public $Entry;
}
// @codingStandardsIgnoreEnd
