<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * PostReplyItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class PostReplyItemType extends PostReplyItemBaseType
{
    /**
     * @var BodyType
     * @access public
     */
    public $NewBodyContent;
}
// @codingStandardsIgnoreEnd
