<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ProtectionRuleConditionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ProtectionRuleConditionType
{
    /**
     * @var string WSDL type is ProtectionRuleAllInternalType
     * @access public
     */
    public $AllInternal;

    /**
     * The name was changed based on a name map provided to the PHP code generation tool
     *
     * @var ProtectionRuleAndType
     * @access public
     */
    public $AndCondition;

    /**
     * @var ProtectionRuleRecipientIsType
     * @access public
     */
    public $RecipientIs;

    /**
     * @var ProtectionRuleSenderDepartmentsType
     * @access public
     */
    public $SenderDepartments;

    /**
     * The name was changed based on a name map provided to the PHP code generation tool
     *
     * @var string WSDL type is ProtectionRuleTrueType
     * @access public
     */
    public $TrueCondition;

    private $_parameterMap = array (
        "And" => "AndCondition",
        "True" => "TrueCondition",
    );
    /**
     * Provided for getting non-php-standard named variables
     * @param string $var The variable name to get
     * @return mixed The variable value
     */
    public function __get($var)
    {
        return $this->{$this->_parameterMap[$var]};
    }

    /**
     * Provided for setting non-php-standard named variables
     * @param string $var The variable name to set
     * @param mixed $value The value to set
     */
    public function __set($var, $value)
    {
        $this->{$this->_parameterMap[$var]} = $value;
    }
}
// @codingStandardsIgnoreEnd
