<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RecipientTrackingEventType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RecipientTrackingEventType
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $Date;

    /**
     * @var EmailAddressType
     * @access public
     */
    public $Recipient;

    /**
     * @var string
     * @access public
     */
    public $DeliveryStatus;

    /**
     * @var string
     * @access public
     */
    public $EventDescription;

    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $EventData;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $Server;

    /**
     * @var integer WSDL type is nonNegativeInteger
     * @access public
     */
    public $InternalId;

    /**
     * @var boolean
     * @access public
     */
    public $BccRecipient;

    /**
     * @var boolean
     * @access public
     */
    public $HiddenRecipient;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $UniquePathId;

    /**
     * @var string WSDL type is NonEmptyStringType
     * @access public
     */
    public $RootAddress;

    /**
     * @var ArrayOfTrackingPropertiesType
     * @access public
     */
    public $Properties;
}
// @codingStandardsIgnoreEnd
