<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RecurringDayTransitionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RecurringDayTransitionType extends RecurringTimeTransitionType
{
    /**
     * @var string
     * @see DayOfWeekType
     * @access public
     */
    public $DayOfWeek;

    /**
     * @var string
     * @access public
     */
    public $Occurrence;
}
// @codingStandardsIgnoreEnd
