<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RecurringTimeTransitionType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RecurringTimeTransitionType extends TransitionType
{
    /**
     * @var duration
     * @access public
     */
    public $TimeOffset;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Month;
}
// @codingStandardsIgnoreEnd
