<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RelativeMonthlyRecurrencePatternType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RelativeMonthlyRecurrencePatternType extends IntervalRecurrencePatternBaseType
{
    /**
     * @var string
     * @see DayOfWeekType
     * @access public
     */
    public $DaysOfWeek;

    /**
     * @var string
     * @see DayOfWeekIndexType
     * @access public
     */
    public $DayOfWeekIndex;
}
// @codingStandardsIgnoreEnd
