<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ReplyBody
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ReplyBody
{
    /**
     * @var string
     * @access public
     */
    public $Message;

    /**
     * @var string WSDL type is lang
     * @access public
     */
    public $lang;
}
// @codingStandardsIgnoreEnd
