<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * RequestTypeHeader
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RequestTypeHeader
{
    /**
     * @var string
     * @see AvailabilityProxyRequestType
     * @access public
     */
    public $RequestType;
}
// @codingStandardsIgnoreEnd
