<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Internal abstract base type for reply objects.
 *         Should not appear in client code
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ResponseObjectCoreType extends MessageType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ReferenceItemId;
}
// @codingStandardsIgnoreEnd
