<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Rule type
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RuleType
{
    /**
     * @var string
     * @access public
     */
    public $RuleId;

    /**
     * @var string
     * @access public
     */
    public $DisplayName;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Priority;

    /**
     * @var boolean
     * @access public
     */
    public $IsEnabled;

    /**
     * @var boolean
     * @access public
     */
    public $IsNotSupported;

    /**
     * @var boolean
     * @access public
     */
    public $IsInError;

    /**
     * @var RulePredicatesType
     * @access public
     */
    public $Conditions;

    /**
     * @var RulePredicatesType
     * @access public
     */
    public $Exceptions;

    /**
     * @var RuleActionsType
     * @access public
     */
    public $Actions;
}
// @codingStandardsIgnoreEnd
