<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Rule actions
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class RuleActionsType
{
    /**
     * @var ArrayOfStringsType
     * @access public
     */
    public $AssignCategories;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $CopyToFolder;

    /**
     * @var boolean
     * @access public
     */
    public $Delete;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $ForwardAsAttachmentToRecipients;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $ForwardToRecipients;

    /**
     * @var string
     * @see ImportanceChoicesType
     * @access public
     */
    public $MarkImportance;

    /**
     * @var boolean
     * @access public
     */
    public $MarkAsRead;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $MoveToFolder;

    /**
     * @var boolean
     * @access public
     */
    public $PermanentDelete;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $RedirectToRecipients;

    /**
     * @var ArrayOfEmailAddressesType
     * @access public
     */
    public $SendSMSAlertToRecipients;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ServerReplyWithMessage;

    /**
     * @var boolean
     * @access public
     */
    public $StopProcessingRules;
}
// @codingStandardsIgnoreEnd
