<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SerializableTimeZoneTime
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SerializableTimeZoneTime
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Bias;

    /**
     * @var string
     * @access public
     */
    public $Time;

    /**
     * @var integer WSDL type is short
     * @access public
     */
    public $DayOrder;

    /**
     * @var integer WSDL type is short
     * @access public
     */
    public $Month;

    /**
     * @var string
     * @see DayOfWeekType
     * @access public
     */
    public $DayOfWeek;

    /**
     * @var string
     * @access public
     */
    public $Year;
}
// @codingStandardsIgnoreEnd
