<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SerializableTimeZone
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SerializableTimeZone
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $Bias;

    /**
     * @var SerializableTimeZoneTime
     * @access public
     */
    public $StandardTime;

    /**
     * @var SerializableTimeZoneTime
     * @access public
     */
    public $DaylightTime;
}
// @codingStandardsIgnoreEnd
