<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * ServiceConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class ServiceConfigurationType
{
    const MAIL_TIPS = "MailTips";
    const UNIFIED_MESSAGING_CONFIGURATION = "UnifiedMessagingConfiguration";
    const PROTECTION_RULES = "ProtectionRules";
}
// @codingStandardsIgnoreEnd
