<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SmtpDomain
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SmtpDomain
{
    /**
     * @var string
     * @access public
     */
    public $Name;

    /**
     * @var boolean
     * @access public
     */
    public $IncludeSubdomains;
}
// @codingStandardsIgnoreEnd
