<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Surfaces the various logon types that are supported for conversion
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SpecialLogonTypeType
{
    const ADMIN = "Admin";
    const SYSTEM_SERVICE = "SystemService";
}
// @codingStandardsIgnoreEnd
