<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Represents standard groupings for GroupBy queries.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class StandardGroupByType
{
    const CONVERSATION_TOPIC = "ConversationTopic";
}
// @codingStandardsIgnoreEnd
