<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SubscribeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SubscribeType extends BaseRequestType
{
    /**
     * @var PullSubscriptionRequestType
     * @access public
     */
    public $PullSubscriptionRequest;

    /**
     * @var PushSubscriptionRequestType
     * @access public
     */
    public $PushSubscriptionRequest;

    /**
     * @var StreamingSubscriptionRequestType
     * @access public
     */
    public $StreamingSubscriptionRequest;
}
// @codingStandardsIgnoreEnd
