<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SuggestionsViewOptionsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SuggestionsViewOptionsType
{
    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $GoodThreshold;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MaximumResultsByDay;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MaximumNonWorkHourResultsByDay;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $MeetingDurationInMinutes;

    /**
     * @var string
     * @see SuggestionQuality
     * @access public
     */
    public $MinimumSuggestionQuality;

    /**
     * @var Duration
     * @access public
     */
    public $DetailedSuggestionsWindow;

    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $CurrentMeetingTime;

    /**
     * @var string
     * @access public
     */
    public $GlobalObjectId;
}
// @codingStandardsIgnoreEnd
