<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * Suggestion
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class Suggestion
{
    /**
     * @var string WSDL type is dateTime
     * @access public
     */
    public $MeetingTime;

    /**
     * @var boolean
     * @access public
     */
    public $IsWorkTime;

    /**
     * @var string
     * @see SuggestionQuality
     * @access public
     */
    public $SuggestionQuality;

    /**
     * @var ArrayOfAttendeeConflictData
     * @access public
     */
    public $AttendeeConflictDataArray;
}
// @codingStandardsIgnoreEnd
