<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SyncFolderItemsReadFlagType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SyncFolderItemsReadFlagType
{
    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var boolean
     * @access public
     */
    public $IsRead;
}
// @codingStandardsIgnoreEnd
