<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SyncFolderHierarchyType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SyncFolderHierarchyType extends BaseRequestType
{
    /**
     * @var FolderResponseShapeType
     * @access public
     */
    public $FolderShape;

    /**
     * @var TargetFolderIdType
     * @access public
     */
    public $SyncFolderId;

    /**
     * @var string
     * @access public
     */
    public $SyncState;
}
// @codingStandardsIgnoreEnd
