<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * SyncFolderHierarchyChangesType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class SyncFolderHierarchyChangesType
{
    /**
     * @var SyncFolderHierarchyCreateOrUpdateType[]
     * @access public
     */
    public $Create;

    /**
     * @var SyncFolderHierarchyCreateOrUpdateType[]
     * @access public
     */
    public $Update;

    /**
     * @var SyncFolderHierarchyDeleteType[]
     * @access public
     */
    public $Delete;
}
// @codingStandardsIgnoreEnd
