<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * TimeChangeType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class TimeChangeType
{
    /**
     * @var duration
     * @access public
     */
    public $Offset;

    /**
     * @var string WSDL type is time
     * @access public
     */
    public $Time;

    /**
     * @var string
     * @access public
     */
    public $TimeZoneName;
}
// @codingStandardsIgnoreEnd
