<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * TimeZoneType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class TimeZoneType
{
    /**
     * @var duration
     * @access public
     */
    public $BaseOffset;

    /**
     * @var TimeChangeType
     * @access public
     */
    public $Standard;

    /**
     * @var TimeChangeType
     * @access public
     */
    public $Daylight;

    /**
     * @var string
     * @access public
     */
    public $TimeZoneName;
}
// @codingStandardsIgnoreEnd
