<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UpdateUserConfigurationType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UpdateUserConfigurationType extends BaseRequestType
{
    /**
     * @var UserConfigurationType
     * @access public
     */
    public $UserConfiguration;
}
// @codingStandardsIgnoreEnd
