<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UpdateItemResponseMessageType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UpdateItemResponseMessageType extends ItemInfoResponseMessageType
{
    /**
     * @var ConflictResultsType
     * @access public
     */
    public $ConflictResults;
}
// @codingStandardsIgnoreEnd
