<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UploadItemType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UploadItemType
{
    /**
     * @var FolderIdType
     * @access public
     */
    public $ParentFolderId;

    /**
     * @var ItemIdType
     * @access public
     */
    public $ItemId;

    /**
     * @var string WSDL type is base64Binary
     * @access public
     */
    public $Data;

    /**
     * @var string
     * @see CreateActionType
     * @access public
     */
    public $CreateAction;

    /**
     * @var boolean
     * @access public
     */
    public $IsAssociated;
}
// @codingStandardsIgnoreEnd
