<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UploadItemsType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UploadItemsType extends BaseRequestType
{
    /**
     * @var NonEmptyArrayOfUploadItemsType
     * @access public
     */
    public $Items;
}
// @codingStandardsIgnoreEnd
