<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserOofSettings
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserOofSettings
{
    /**
     * @var string
     * @see OofState
     * @access public
     */
    public $OofState;

    /**
     * @var string
     * @see ExternalAudience
     * @access public
     */
    public $ExternalAudience;

    /**
     * @var Duration
     * @access public
     */
    public $Duration;

    /**
     * @var ReplyBody
     * @access public
     */
    public $InternalReply;

    /**
     * @var ReplyBody
     * @access public
     */
    public $ExternalReply;
}
// @codingStandardsIgnoreEnd
