<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * UserIdType
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserIdType
{
    /**
     * @var string
     * @access public
     */
    public $SID;

    /**
     * @var string
     * @access public
     */
    public $PrimarySmtpAddress;

    /**
     * @var string
     * @access public
     */
    public $DisplayName;

    /**
     * @var string
     * @see DistinguishedUserType
     * @access public
     */
    public $DistinguishedUser;

    /**
     * @var string
     * @access public
     */
    public $ExternalUserIdentity;
}
// @codingStandardsIgnoreEnd
