<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * User Mailbox.
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class UserMailboxType
{
    /**
     * @var string
     * @access public
     */
    public $Id;

    /**
     * @var boolean
     * @access public
     */
    public $IsArchive;
}
// @codingStandardsIgnoreEnd
