<?php

namespace OroPro\Bundle\EwsBundle\Ews\EwsType;

// @codingStandardsIgnoreStart
/**
 * WorkingPeriod
 *
 * @ignore This code was generated by a tool.
 *         Changes to this file may cause incorrect behaviour and will be lost if
 *         the code is regenerated.
 * @SuppressWarnings(PHPMD)
 */
class WorkingPeriod
{
    /**
     * @var string can contain multiple values (values are separated by a space character) of DayOfWeekType
     * @see DayOfWeekType
     * @access public
     */
    public $DayOfWeek;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $StartTimeInMinutes;

    /**
     * @var integer WSDL type is int
     * @access public
     */
    public $EndTimeInMinutes;
}
// @codingStandardsIgnoreEnd
